import { C_ADD_FRIEND_1 } from '../defs/C_ADD_FRIEND_1';
import { C_ADD_TELEPORT_TO_POS_LIST_1 } from '../defs/C_ADD_TELEPORT_TO_POS_LIST_1';
import { C_ADMIN_1 } from '../defs/C_ADMIN_1';
import { C_APPLY_PARTY_1 } from '../defs/C_APPLY_PARTY_1';
import { C_ASK_INTERACTIVE_2 } from '../defs/C_ASK_INTERACTIVE_2';
import { C_BAN_PARTY_MEMBER_1 } from '../defs/C_BAN_PARTY_MEMBER_1';
import { C_BIND_ITEM_BEGIN_PROGRESS_1 } from '../defs/C_BIND_ITEM_BEGIN_PROGRESS_1';
import { C_BIND_ITEM_EXECUTE_1 } from '../defs/C_BIND_ITEM_EXECUTE_1';
import { C_BLOCK_USER_1 } from '../defs/C_BLOCK_USER_1';
import { C_CANCEL_CHANGE_USER_APPEARANCE_1 } from '../defs/C_CANCEL_CHANGE_USER_APPEARANCE_1';
import { C_CANCEL_CONTRACT_1 } from '../defs/C_CANCEL_CONTRACT_1';
import { C_CHANGE_PARTY_MEMBER_AUTHORITY_1 } from '../defs/C_CHANGE_PARTY_MEMBER_AUTHORITY_1';
import { C_CHAT_1 } from '../defs/C_CHAT_1';
import { C_CHECK_VERSION_1 } from '../defs/C_CHECK_VERSION_1';
import { C_COMPLETE_DAILY_EVENT_1 } from '../defs/C_COMPLETE_DAILY_EVENT_1';
import { C_COMPLETE_EXTRA_EVENT_1 } from '../defs/C_COMPLETE_EXTRA_EVENT_1';
import { C_CONFIRM_UPDATE_NOTIFICATION_1 } from '../defs/C_CONFIRM_UPDATE_NOTIFICATION_1';
import { C_DELETE_FRIEND_1 } from '../defs/C_DELETE_FRIEND_1';
import { C_DELETE_TELEPORT_TO_POS_LIST_1 } from '../defs/C_DELETE_TELEPORT_TO_POS_LIST_1';
import { C_DIALOG_1 } from '../defs/C_DIALOG_1';
import { C_DISMISS_PARTY_1 } from '../defs/C_DISMISS_PARTY_1';
import { C_EDIT_BLOCKED_USER_MEMO_1 } from '../defs/C_EDIT_BLOCKED_USER_MEMO_1';
import { C_END_MOVIE_1 } from '../defs/C_END_MOVIE_1';
import { C_GACHA_CANCEL_1 } from '../defs/C_GACHA_CANCEL_1';
import { C_GACHA_TRY_1 } from '../defs/C_GACHA_TRY_1';
import { C_GET_IN_SHUTTLE_1 } from '../defs/C_GET_IN_SHUTTLE_1';
import { C_GET_OUT_SHUTTLE_1 } from '../defs/C_GET_OUT_SHUTTLE_1';
import { C_GET_USER_LIST_1 } from '../defs/C_GET_USER_LIST_1';
import { C_INVITE_USER_TO_GUILD_1 } from '../defs/C_INVITE_USER_TO_GUILD_1';
import { C_ITEM_COLORING_SET_COLOR_2 } from '../defs/C_ITEM_COLORING_SET_COLOR_2';
import { C_LEAVE_PARTY_1 } from '../defs/C_LEAVE_PARTY_1';
import { C_LEAVE_PRIVATE_CHANNEL_1 } from '../defs/C_LEAVE_PRIVATE_CHANNEL_1';
import { C_LOAD_TOPO_FIN_1 } from '../defs/C_LOAD_TOPO_FIN_1';
import { C_MERGE_ITEM_EXECUTE_1 } from '../defs/C_MERGE_ITEM_EXECUTE_1';
import { C_OP_COMMAND_1 } from '../defs/C_OP_COMMAND_1';
import { C_PARTY_APPLICATION_DENIED_1 } from '../defs/C_PARTY_APPLICATION_DENIED_1';
import { C_PARTY_MARKER_1 } from '../defs/C_PARTY_MARKER_1';
import { C_PARTY_MATCH_WINDOW_CLOSED_1 } from '../defs/C_PARTY_MATCH_WINDOW_CLOSED_1';
import { C_REGISTER_ENCHANT_ITEM_1 } from '../defs/C_REGISTER_ENCHANT_ITEM_1';
import { C_REGISTER_EVOLUTION_ITEM_1 } from '../defs/C_REGISTER_EVOLUTION_ITEM_1';
import { C_REGISTER_PARTY_INFO_1 } from '../defs/C_REGISTER_PARTY_INFO_1';
import { C_REMOVE_BLOCKED_USER_1 } from '../defs/C_REMOVE_BLOCKED_USER_1';
import { C_REPLY_THROUGH_ARBITER_CONTRACT_1 } from '../defs/C_REPLY_THROUGH_ARBITER_CONTRACT_1';
import { C_REQUEST_ABNORMALITY_TOOLTIP_VALUE_1 } from '../defs/C_REQUEST_ABNORMALITY_TOOLTIP_VALUE_1';
import { C_REQUEST_CANDIDATE_LIST_1 } from '../defs/C_REQUEST_CANDIDATE_LIST_1';
import { C_REQUEST_CONTRACT_1 } from '../defs/C_REQUEST_CONTRACT_1';
import { C_REQUEST_ENCHANT_1 } from '../defs/C_REQUEST_ENCHANT_1';
import { C_REQUEST_EVOLUTION_1 } from '../defs/C_REQUEST_EVOLUTION_1';
import { C_REQUEST_GAMESTAT_PING_1 } from '../defs/C_REQUEST_GAMESTAT_PING_1';
import { C_REQUEST_NONDB_ITEM_INFO_2 } from '../defs/C_REQUEST_NONDB_ITEM_INFO_2';
import { C_REQUEST_PARTY_MATCH_INFO_1 } from '../defs/C_REQUEST_PARTY_MATCH_INFO_1';
import { C_REQUEST_PARTY_MATCH_INFO_PAGE_1 } from '../defs/C_REQUEST_PARTY_MATCH_INFO_PAGE_1';
import { C_REQUEST_PARTY_MATCH_LINK_1 } from '../defs/C_REQUEST_PARTY_MATCH_LINK_1';
import { C_RESET_ALL_DUNGEON_1 } from '../defs/C_RESET_ALL_DUNGEON_1';
import { C_RETURN_TO_LOBBY_1 } from '../defs/C_RETURN_TO_LOBBY_1';
import { C_RQ_COMMIT_DECOMPOSITION_CONTRACT_1 } from '../defs/C_RQ_COMMIT_DECOMPOSITION_CONTRACT_1';
import { C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION_1 } from '../defs/C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION_1';
import { C_SAVE_CLIENT_ACCOUNT_SETTING_1 } from '../defs/C_SAVE_CLIENT_ACCOUNT_SETTING_1';
import { C_SECOND_PASSWORD_AUTH_1 } from '../defs/C_SECOND_PASSWORD_AUTH_1';
import { C_SELECT_USER_1 } from '../defs/C_SELECT_USER_1';
import { C_SET_VISIBLE_RANGE_1 } from '../defs/C_SET_VISIBLE_RANGE_1';
import { C_SHOW_ITEMLIST_1 } from '../defs/C_SHOW_ITEMLIST_1';
import { C_SOCIAL_1 } from '../defs/C_SOCIAL_1';
import { C_START_ENCHANT_1 } from '../defs/C_START_ENCHANT_1';
import { C_START_EVOLUTION_1 } from '../defs/C_START_EVOLUTION_1';
import { C_START_PRODUCE_1 } from '../defs/C_START_PRODUCE_1';
import { C_TELEPORT_TO_POS_1 } from '../defs/C_TELEPORT_TO_POS_1';
import { C_TELEPORT_TO_VILLAGE_1 } from '../defs/C_TELEPORT_TO_VILLAGE_1';
import { C_TRADE_BROKER_DEAL_CONFIRM_1 } from '../defs/C_TRADE_BROKER_DEAL_CONFIRM_1';
import { C_TRADE_BROKER_REJECT_SUGGEST_1 } from '../defs/C_TRADE_BROKER_REJECT_SUGGEST_1';
import { C_TRADE_BROKER_SUGGEST_DEAL_1 } from '../defs/C_TRADE_BROKER_SUGGEST_DEAL_1';
import { C_TRADE_BROKER_WAITING_ITEM_LIST_NEW_1 } from '../defs/C_TRADE_BROKER_WAITING_ITEM_LIST_NEW_1';
import { C_TRADE_BROKER_WAITING_ITEM_LIST_PAGE_1 } from '../defs/C_TRADE_BROKER_WAITING_ITEM_LIST_PAGE_1';
import { C_UNMOUNT_VEHICLE_1 } from '../defs/C_UNMOUNT_VEHICLE_1';
import { C_UNREGISTER_ENCHANT_ITEM_1 } from '../defs/C_UNREGISTER_ENCHANT_ITEM_1';
import { C_UNREGISTER_EVOLUTION_ITEM_1 } from '../defs/C_UNREGISTER_EVOLUTION_ITEM_1';
import { C_UNREGISTER_PARTY_INFO_1 } from '../defs/C_UNREGISTER_PARTY_INFO_1';
import { C_UPDATE_REACTION_POS_1 } from '../defs/C_UPDATE_REACTION_POS_1';
import { C_USE_PREMIUM_SLOT_1 } from '../defs/C_USE_PREMIUM_SLOT_1';
import { C_VISIT_NEW_SECTION_1 } from '../defs/C_VISIT_NEW_SECTION_1';
import { C_WHISPER_1 } from '../defs/C_WHISPER_1';
import { S_ABNORMALITY_DAMAGE_ABSORB_1 } from '../defs/S_ABNORMALITY_DAMAGE_ABSORB_1';
import { S_ABNORMALITY_END_1 } from '../defs/S_ABNORMALITY_END_1';
import { S_ABNORMALITY_REFRESH_2 } from '../defs/S_ABNORMALITY_REFRESH_2';
import { S_ABNORMALITY_RESIST_1 } from '../defs/S_ABNORMALITY_RESIST_1';
import { S_ABNORMALITY_TOOLTIP_VALUE_1 } from '../defs/S_ABNORMALITY_TOOLTIP_VALUE_1';
import { S_ACCEPT_CONTRACT_1 } from '../defs/S_ACCEPT_CONTRACT_1';
import { S_ADD_INTER_PARTY_MATCH_POOL_1 } from '../defs/S_ADD_INTER_PARTY_MATCH_POOL_1';
import { S_AERO_1 } from '../defs/S_AERO_1';
import { S_AIR_REACTION_END_1 } from '../defs/S_AIR_REACTION_END_1';
import { S_ANNOUNCE_UPDATE_NOTIFICATION_1 } from '../defs/S_ANNOUNCE_UPDATE_NOTIFICATION_1';
import { S_ASK_BIDDING_RARE_ITEM_1 } from '../defs/S_ASK_BIDDING_RARE_ITEM_1';
import { S_ASK_TELEPORT_1 } from '../defs/S_ASK_TELEPORT_1';
import { S_AVAILABLE_EVENT_MATCHING_LIST_2 } from '../defs/S_AVAILABLE_EVENT_MATCHING_LIST_2';
import { S_BAN_PARTY_MEMBER_1 } from '../defs/S_BAN_PARTY_MEMBER_1';
import { S_BATTLE_FIELD_ENTRANCE_INFO_1 } from '../defs/S_BATTLE_FIELD_ENTRANCE_INFO_1';
import { S_BATTLE_FIELD_POINT_STORE_SELL_LIST_1 } from '../defs/S_BATTLE_FIELD_POINT_STORE_SELL_LIST_1';
import { S_BEGIN_THROUGH_ARBITER_CONTRACT_1 } from '../defs/S_BEGIN_THROUGH_ARBITER_CONTRACT_1';
import { S_CANCEL_CONTRACT_1 } from '../defs/S_CANCEL_CONTRACT_1';
import { S_CHANGE_EP_EXP_DAILY_LIMIT_1 } from '../defs/S_CHANGE_EP_EXP_DAILY_LIMIT_1';
import { S_CHANGE_EP_POINT_1 } from '../defs/S_CHANGE_EP_POINT_1';
import { S_CHANGE_FRIEND_STATE_1 } from '../defs/S_CHANGE_FRIEND_STATE_1';
import { S_CHANGE_GUILD_CHIEF_1 } from '../defs/S_CHANGE_GUILD_CHIEF_1';
import { S_CHANGE_VOICE_USE_QAC_1 } from '../defs/S_CHANGE_VOICE_USE_QAC_1';
import { S_CHECK_VERSION_1 } from '../defs/S_CHECK_VERSION_1';
import { S_CLEAR_ALL_HOLDED_ABNORMALITY_1 } from '../defs/S_CLEAR_ALL_HOLDED_ABNORMALITY_1';
import { S_COMPLETE_EVENT_MATCHING_QUEST_1 } from '../defs/S_COMPLETE_EVENT_MATCHING_QUEST_1';
import { S_CUSTOM_STYLE_SYSTEM_MESSAGE_1 } from '../defs/S_CUSTOM_STYLE_SYSTEM_MESSAGE_1';
import { S_DELETE_FRIEND_1 } from '../defs/S_DELETE_FRIEND_1';
import { S_DESPAWN_EVENT_SEED_1 } from '../defs/S_DESPAWN_EVENT_SEED_1';
import { S_DESPAWN_PROJECTILE_2 } from '../defs/S_DESPAWN_PROJECTILE_2';
import { S_DESTROY_GUILD_TOWER_1 } from '../defs/S_DESTROY_GUILD_TOWER_1';
import { S_DUNGEON_CAMERA_SET_1 } from '../defs/S_DUNGEON_CAMERA_SET_1';
import { S_DUNGEON_CLEAR_COUNT_LIST_1 } from '../defs/S_DUNGEON_CLEAR_COUNT_LIST_1';
import { S_END_CHANGE_USER_APPEARANCE_1 } from '../defs/S_END_CHANGE_USER_APPEARANCE_1';
import { S_END_PRODUCE_1 } from '../defs/S_END_PRODUCE_1';
import { S_EP_SYSTEM_DAILY_EVENT_EXP_ON_OFF_1 } from '../defs/S_EP_SYSTEM_DAILY_EVENT_EXP_ON_OFF_1';
import { S_F2P_PremiumUser_Permission_1 } from '../defs/S_F2P_PremiumUser_Permission_1';
import { S_FACIAL_ATTACHMENT_BROADCAST_1 } from '../defs/S_FACIAL_ATTACHMENT_BROADCAST_1';
import { S_FIELD_EVENT_PROGRESS_INFO_1 } from '../defs/S_FIELD_EVENT_PROGRESS_INFO_1';
import { S_FIN_INTER_PARTY_MATCH_1 } from '../defs/S_FIN_INTER_PARTY_MATCH_1';
import { S_FIX_VEHICLE_PROGRESS_1 } from '../defs/S_FIX_VEHICLE_PROGRESS_1';
import { S_FRIEND_LIST_1 } from '../defs/S_FRIEND_LIST_1';
import { S_GET_IN_SHUTTLE_1 } from '../defs/S_GET_IN_SHUTTLE_1';
import { S_GET_OUT_SHUTTLE_1 } from '../defs/S_GET_OUT_SHUTTLE_1';
import { S_GET_USER_GUILD_LOGO_1 } from '../defs/S_GET_USER_GUILD_LOGO_1';
import { S_GMEVENT_GUIDE_MESSAGE_1 } from '../defs/S_GMEVENT_GUIDE_MESSAGE_1';
import { S_GMEVENT_OX_QUIZ_OPEN_1 } from '../defs/S_GMEVENT_OX_QUIZ_OPEN_1';
import { S_GMEVENT_OX_QUIZ_RESULT_1 } from '../defs/S_GMEVENT_OX_QUIZ_RESULT_1';
import { S_GROUP_NPC_LOCATION_1 } from '../defs/S_GROUP_NPC_LOCATION_1';
import { S_GUILD_MEMBER_LIST_1 } from '../defs/S_GUILD_MEMBER_LIST_1';
import { S_GUILD_STORE_SELL_LIST_1 } from '../defs/S_GUILD_STORE_SELL_LIST_1';
import { S_HIT_COMBO_1 } from '../defs/S_HIT_COMBO_1';
import { S_IMAGE_DATA_1 } from '../defs/S_IMAGE_DATA_1';
import { S_INVEN_CHANGEDSLOT_1 } from '../defs/S_INVEN_CHANGEDSLOT_1';
import { S_ITEM_COLORING_BAG_1 } from '../defs/S_ITEM_COLORING_BAG_1';
import { S_LEARN_EP_PERK_1 } from '../defs/S_LEARN_EP_PERK_1';
import { S_LEAVE_GUILD_1 } from '../defs/S_LEAVE_GUILD_1';
import { S_LEAVE_PARTY_1 } from '../defs/S_LEAVE_PARTY_1';
import { S_LOAD_ACHIEVEMENT_LIST_2 } from '../defs/S_LOAD_ACHIEVEMENT_LIST_2';
import { S_LOAD_CLIENT_ACCOUNT_SETTING_1 } from '../defs/S_LOAD_CLIENT_ACCOUNT_SETTING_1';
import { S_LOAD_CLIENT_USER_SETTING_1 } from '../defs/S_LOAD_CLIENT_USER_SETTING_1';
import { S_LOAD_EP_INFO_1 } from '../defs/S_LOAD_EP_INFO_1';
import { S_LOAD_TELEPORT_TO_POS_LIST_1 } from '../defs/S_LOAD_TELEPORT_TO_POS_LIST_1';
import { S_LOCKON_YOU_1 } from '../defs/S_LOCKON_YOU_1';
import { S_LOGOUT_PARTY_MEMBER_1 } from '../defs/S_LOGOUT_PARTY_MEMBER_1';
import { S_MOUNT_VEHICLE_EX_1 } from '../defs/S_MOUNT_VEHICLE_EX_1';
import { S_MOVE_SHUTTLE_1 } from '../defs/S_MOVE_SHUTTLE_1';
import { S_NOCTAN_VARIATION_INFO_1 } from '../defs/S_NOCTAN_VARIATION_INFO_1';
import { S_NOTIFY_GUILD_QUEST_URGENT_1 } from '../defs/S_NOTIFY_GUILD_QUEST_URGENT_1';
import { S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA_1 } from '../defs/S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA_1';
import { S_NPC_MENU_SELECT_1 } from '../defs/S_NPC_MENU_SELECT_1';
import { S_NPC_OCCUPIER_INFO_1 } from '../defs/S_NPC_OCCUPIER_INFO_1';
import { S_NPC_TARGET_USER_1 } from '../defs/S_NPC_TARGET_USER_1';
import { S_OPEN_AWESOMIUM_WEB_URL_1 } from '../defs/S_OPEN_AWESOMIUM_WEB_URL_1';
import { S_OTHER_USER_APPLY_PARTY_1 } from '../defs/S_OTHER_USER_APPLY_PARTY_1';
import { S_PARTY_INFO_1 } from '../defs/S_PARTY_INFO_1';
import { S_PARTY_MARKER_1 } from '../defs/S_PARTY_MARKER_1';
import { S_PARTY_MEMBER_ABNORMAL_CLEAR_1 } from '../defs/S_PARTY_MEMBER_ABNORMAL_CLEAR_1';
import { S_PARTY_MEMBER_INFO_3 } from '../defs/S_PARTY_MEMBER_INFO_3';
import { S_PLAYER_CHANGE_EP_1 } from '../defs/S_PLAYER_CHANGE_EP_1';
import { S_PLAYER_CHANGE_FLIGHT_ENERGY_1 } from '../defs/S_PLAYER_CHANGE_FLIGHT_ENERGY_1';
import { S_PLAYER_CHANGE_MP_1 } from '../defs/S_PLAYER_CHANGE_MP_1';
import { S_PLAYER_CHANGE_STAMINA_1 } from '../defs/S_PLAYER_CHANGE_STAMINA_1';
import { S_PLAYER_RESET_EP_1 } from '../defs/S_PLAYER_RESET_EP_1';
import { S_PLAY_ANIMATION_1 } from '../defs/S_PLAY_ANIMATION_1';
import { S_PLAY_EFFECT_1 } from '../defs/S_PLAY_EFFECT_1';
import { S_PLAY_MOVIE_1 } from '../defs/S_PLAY_MOVIE_1';
import { S_PLAY_SOUND_1 } from '../defs/S_PLAY_SOUND_1';
import { S_POINT_STORE_SELL_LIST_1 } from '../defs/S_POINT_STORE_SELL_LIST_1';
import { S_PREMIUM_SLOT_OFF_1 } from '../defs/S_PREMIUM_SLOT_OFF_1';
import { S_PREPARE_EXIT_1 } from '../defs/S_PREPARE_EXIT_1';
import { S_PREPARE_RETURN_TO_LOBBY_1 } from '../defs/S_PREPARE_RETURN_TO_LOBBY_1';
import { S_PREVIEW_ITEM_1 } from '../defs/S_PREVIEW_ITEM_1';
import { S_PRIVATE_CHAT_1 } from '../defs/S_PRIVATE_CHAT_1';
import { S_PRODUCE_CRITICAL_1 } from '../defs/S_PRODUCE_CRITICAL_1';
import { S_QUEST_BALLOON_1 } from '../defs/S_QUEST_BALLOON_1';
import { S_REJECT_CONTRACT_1 } from '../defs/S_REJECT_CONTRACT_1';
import { S_REMOVE_BLOCKED_USER_1 } from '../defs/S_REMOVE_BLOCKED_USER_1';
import { S_REMOVE_EFFECT_1 } from '../defs/S_REMOVE_EFFECT_1';
import { S_REPLY_NONDB_ITEM_INFO_1 } from '../defs/S_REPLY_NONDB_ITEM_INFO_1';
import { S_REPLY_REQUEST_CONTRACT_1 } from '../defs/S_REPLY_REQUEST_CONTRACT_1';
import { S_REQUEST_CITY_WAR_MAP_INFO_1 } from '../defs/S_REQUEST_CITY_WAR_MAP_INFO_1';
import { S_REQUEST_CITY_WAR_MAP_INFO_DETAIL_1 } from '../defs/S_REQUEST_CITY_WAR_MAP_INFO_DETAIL_1';
import { S_REQUEST_CITY_WAR_MAP_INFO_END_1 } from '../defs/S_REQUEST_CITY_WAR_MAP_INFO_END_1';
import { S_REQUEST_CONTRACT_1 } from '../defs/S_REQUEST_CONTRACT_1';
import { S_REQUEST_DESPAWN_SERVANT_1 } from '../defs/S_REQUEST_DESPAWN_SERVANT_1';
import { S_REQUEST_REACTION_POS_TICK_1 } from '../defs/S_REQUEST_REACTION_POS_TICK_1';
import { S_REQUEST_SECOND_PASSWORD_AUTH_1 } from '../defs/S_REQUEST_SECOND_PASSWORD_AUTH_1';
import { S_REQUEST_STYLE_SHOP_MARK_PRODUCTLIST_1 } from '../defs/S_REQUEST_STYLE_SHOP_MARK_PRODUCTLIST_1';
import { S_RESET_EP_PERK_1 } from '../defs/S_RESET_EP_PERK_1';
import { S_RESPONSE_GAMESTAT_PONG_1 } from '../defs/S_RESPONSE_GAMESTAT_PONG_1';
import { S_RESULT_BIDDING_DICE_THROW_1 } from '../defs/S_RESULT_BIDDING_DICE_THROW_1';
import { S_RESULT_ITEM_BIDDING_1 } from '../defs/S_RESULT_ITEM_BIDDING_1';
import { S_RETURN_TO_LOBBY_1 } from '../defs/S_RETURN_TO_LOBBY_1';
import { S_RP_SKILL_POLISHING_LIST_1 } from '../defs/S_RP_SKILL_POLISHING_LIST_1';
import { S_SHOW_AWESOMIUMWEB_SHOP_1 } from '../defs/S_SHOW_AWESOMIUMWEB_SHOP_1';
import { S_SHOW_PARTY_MATCH_INFO_1 } from '../defs/S_SHOW_PARTY_MATCH_INFO_1';
import { S_SHOW_PEGASUS_MAP_1 } from '../defs/S_SHOW_PEGASUS_MAP_1';
import { S_SHOW_USER_EP_INFO_1 } from '../defs/S_SHOW_USER_EP_INFO_1';
import { S_SKILL_ATTENTION_TARGET_1 } from '../defs/S_SKILL_ATTENTION_TARGET_1';
import { S_SOCIAL_1 } from '../defs/S_SOCIAL_1';
import { S_START_CLIMBING_1 } from '../defs/S_START_CLIMBING_1';
import { S_START_COOLTIME_ITEM_1 } from '../defs/S_START_COOLTIME_ITEM_1';
import { S_STICK_TO_USER_START_1 } from '../defs/S_STICK_TO_USER_START_1';
import { S_STORE_SELL_LIST_1 } from '../defs/S_STORE_SELL_LIST_1';
import { S_SUCCESS_COUNTER_1 } from '../defs/S_SUCCESS_COUNTER_1';
import { S_SYSTEM_MESSAGE_1 } from '../defs/S_SYSTEM_MESSAGE_1';
import { S_SYSTEM_MESSAGE_LOOT_ITEM_1 } from '../defs/S_SYSTEM_MESSAGE_LOOT_ITEM_1';
import { S_SYSTEM_MESSAGE_LOOT_SPECIAL_ITEM_1 } from '../defs/S_SYSTEM_MESSAGE_LOOT_SPECIAL_ITEM_1';
import { S_TELEPORT_TO_CAMP_1 } from '../defs/S_TELEPORT_TO_CAMP_1';
import { S_TRADE_BROKER_DEAL_INFO_UPDATE_1 } from '../defs/S_TRADE_BROKER_DEAL_INFO_UPDATE_1';
import { S_TRADE_BROKER_DEAL_SUGGESTED_1 } from '../defs/S_TRADE_BROKER_DEAL_SUGGESTED_1';
import { S_TRADE_BROKER_REQUEST_DEAL_RESULT_1 } from '../defs/S_TRADE_BROKER_REQUEST_DEAL_RESULT_1';
import { S_TRADE_BROKER_SUGGEST_DEAL_1 } from '../defs/S_TRADE_BROKER_SUGGEST_DEAL_1';
import { S_TRADE_BROKER_WAITING_ITEM_LIST_1 } from '../defs/S_TRADE_BROKER_WAITING_ITEM_LIST_1';
import { S_UNMOUNT_VEHICLE_EX_1 } from '../defs/S_UNMOUNT_VEHICLE_EX_1';
import { S_UPDATE_ACHIEVEMENT_PROGRESS_1 } from '../defs/S_UPDATE_ACHIEVEMENT_PROGRESS_1';
import { S_UPDATE_FRIEND_INFO_1 } from '../defs/S_UPDATE_FRIEND_INFO_1';
import { S_UPDATE_GUILD_QUEST_STATUS_1 } from '../defs/S_UPDATE_GUILD_QUEST_STATUS_1';
import { S_USER_APPEARANCE_CHANGE_1 } from '../defs/S_USER_APPEARANCE_CHANGE_1';
import { S_USER_CHANGE_NAME_1 } from '../defs/S_USER_CHANGE_NAME_1';
import { S_USER_EFFECT_1 } from '../defs/S_USER_EFFECT_1';
import { S_USER_MOVETYPE_1 } from '../defs/S_USER_MOVETYPE_1';
import { S_USER_SITUATION_1 } from '../defs/S_USER_SITUATION_1';
import { S_VILLAGE_LIST_TO_TELEPORT_1 } from '../defs/S_VILLAGE_LIST_TO_TELEPORT_1';
import { S_VISIT_NEW_SECTION_1 } from '../defs/S_VISIT_NEW_SECTION_1';
import { S_VOTE_RESET_ALL_DUNGEON_1 } from '../defs/S_VOTE_RESET_ALL_DUNGEON_1';
import { S_WEAK_POINT_1 } from '../defs/S_WEAK_POINT_1';
import { C_CHANGE_PARTY_MANAGER_2 } from '../defs/C_CHANGE_PARTY_MANAGER_2';
import { C_COMMIT_CHANGE_USER_APPEARANCE_2 } from '../defs/C_COMMIT_CHANGE_USER_APPEARANCE_2';
import { C_CREST_APPLY_2 } from '../defs/C_CREST_APPLY_2';
import { C_CREST_APPLY_LIST_2 } from '../defs/C_CREST_APPLY_LIST_2';
import { C_END_CLIMBING_2 } from '../defs/C_END_CLIMBING_2';
import { C_LOGIN_ARBITER_2 } from '../defs/C_LOGIN_ARBITER_2';
import { C_MERGE_ITEM_2 } from '../defs/C_MERGE_ITEM_2';
import { C_NPC_CONTACT_2 } from '../defs/C_NPC_CONTACT_2';
import { C_REQUEST_PARTY_INFO_2 } from '../defs/C_REQUEST_PARTY_INFO_2';
import { C_REQUEST_PRIVATE_CHANNEL_INFO_2 } from '../defs/C_REQUEST_PRIVATE_CHANNEL_INFO_2';
import { C_REQUEST_USER_PAPERDOLL_INFO_3 } from '../defs/C_REQUEST_USER_PAPERDOLL_INFO_3';
import { C_REQUEST_USER_PAPERDOLL_INFO_WITH_GAMEID_3 } from '../defs/C_REQUEST_USER_PAPERDOLL_INFO_WITH_GAMEID_3';
import { C_REVIVE_NOW_2 } from '../defs/C_REVIVE_NOW_2';
import { C_TRADE_BROKER_BUY_IT_NOW_2 } from '../defs/C_TRADE_BROKER_BUY_IT_NOW_2';
import { C_VIEW_WARE_2 } from '../defs/C_VIEW_WARE_2';
import { S_ABNORMALITY_FAIL_2 } from '../defs/S_ABNORMALITY_FAIL_2';
import { S_ABNORMALITY_SCALE_UP_2 } from '../defs/S_ABNORMALITY_SCALE_UP_2';
import { S_ADD_BLOCKED_USER_2 } from '../defs/S_ADD_BLOCKED_USER_2';
import { S_ADMIN_HOLD_CHARACTER_2 } from '../defs/S_ADMIN_HOLD_CHARACTER_2';
import { S_ANSWER_INTERACTIVE_2 } from '../defs/S_ANSWER_INTERACTIVE_2';
import { S_AVAILABLE_SOCIAL_LIST_2 } from '../defs/S_AVAILABLE_SOCIAL_LIST_2';
import { S_CHANGE_EVENT_MATCHING_STATE_2 } from '../defs/S_CHANGE_EVENT_MATCHING_STATE_2';
import { S_CHANGE_PARTY_MANAGER_2 } from '../defs/S_CHANGE_PARTY_MANAGER_2';
import { S_COLLECTION_PICKEND_2 } from '../defs/S_COLLECTION_PICKEND_2';
import { S_COLLECTION_PICKSTART_2 } from '../defs/S_COLLECTION_PICKSTART_2';
import { S_CREATURE_ROTATE_2 } from '../defs/S_CREATURE_ROTATE_2';
import { S_CREST_APPLY_2 } from '../defs/S_CREST_APPLY_2';
import { S_CREST_INFO_2 } from '../defs/S_CREST_INFO_2';
import { S_CREST_MESSAGE_2 } from '../defs/S_CREST_MESSAGE_2';
import { S_CURRENT_CHANNEL_2 } from '../defs/S_CURRENT_CHANNEL_2';
import { S_DEAD_LOCATION_2 } from '../defs/S_DEAD_LOCATION_2';
import { S_DESPAWN_BONFIRE_2 } from '../defs/S_DESPAWN_BONFIRE_2';
import { S_DESPAWN_BUILD_OBJECT_2 } from '../defs/S_DESPAWN_BUILD_OBJECT_2';
import { S_DESPAWN_COLLECTION_2 } from '../defs/S_DESPAWN_COLLECTION_2';
import { S_DESPAWN_SHUTTLE_2 } from '../defs/S_DESPAWN_SHUTTLE_2';
import { S_DUNGEON_COOL_TIME_LIST_2 } from '../defs/S_DUNGEON_COOL_TIME_LIST_2';
import { S_DUNGEON_EVENT_MESSAGE_2 } from '../defs/S_DUNGEON_EVENT_MESSAGE_2';
import { S_ENABLE_DISABLE_SELLABLE_ITEM_LIST_2 } from '../defs/S_ENABLE_DISABLE_SELLABLE_ITEM_LIST_2';
import { S_FEARMOVE_END_2 } from '../defs/S_FEARMOVE_END_2';
import { S_FEARMOVE_STAGE_2 } from '../defs/S_FEARMOVE_STAGE_2';
import { S_FIELD_POINT_INFO_2 } from '../defs/S_FIELD_POINT_INFO_2';
import { S_GACHA_END_2 } from '../defs/S_GACHA_END_2';
import { S_GACHA_START_2 } from '../defs/S_GACHA_START_2';
import { S_GMEVENT_RECV_REWARD_2 } from '../defs/S_GMEVENT_RECV_REWARD_2';
import { S_GUILD_NAME_2 } from '../defs/S_GUILD_NAME_2';
import { S_HOLD_ABNORMALITY_ADD_2 } from '../defs/S_HOLD_ABNORMALITY_ADD_2';
import { S_INVEN_USERDATA_2 } from '../defs/S_INVEN_USERDATA_2';
import { S_ITEM_CUSTOM_STRING_2 } from '../defs/S_ITEM_CUSTOM_STRING_2';
import { S_ITEM_EXPLOSION_RESULT_2 } from '../defs/S_ITEM_EXPLOSION_RESULT_2';
import { S_JOIN_PRIVATE_CHANNEL_2 } from '../defs/S_JOIN_PRIVATE_CHANNEL_2';
import { S_LEAVE_PARTY_MEMBER_2 } from '../defs/S_LEAVE_PARTY_MEMBER_2';
import { S_LEAVE_PRIVATE_CHANNEL_2 } from '../defs/S_LEAVE_PRIVATE_CHANNEL_2';
import { S_LOADING_SCREEN_CONTROL_INFO_2 } from '../defs/S_LOADING_SCREEN_CONTROL_INFO_2';
import { S_LOAD_DUNGEON_SOUND_HINT_2 } from '../defs/S_LOAD_DUNGEON_SOUND_HINT_2';
import { S_LOGIN_ACCOUNT_INFO_2 } from '../defs/S_LOGIN_ACCOUNT_INFO_2';
import { S_MOUNT_VEHICLE_2 } from '../defs/S_MOUNT_VEHICLE_2';
import { S_MUTE_2 } from '../defs/S_MUTE_2';
import { S_NPCGUILD_LIST_2 } from '../defs/S_NPCGUILD_LIST_2';
import { S_NPC_STATUS_2 } from '../defs/S_NPC_STATUS_2';
import { S_PARTY_MATCH_LINK_2 } from '../defs/S_PARTY_MATCH_LINK_2';
import { S_PARTY_MEMBER_ABNORMAL_DEL_2 } from '../defs/S_PARTY_MEMBER_ABNORMAL_DEL_2';
import { S_PARTY_MEMBER_BUFF_UPDATE_2 } from '../defs/S_PARTY_MEMBER_BUFF_UPDATE_2';
import { S_PARTY_MEMBER_CHANGE_MP_2 } from '../defs/S_PARTY_MEMBER_CHANGE_MP_2';
import { S_PARTY_MEMBER_CHANGE_STAMINA_2 } from '../defs/S_PARTY_MEMBER_CHANGE_STAMINA_2';
import { S_PLAYER_CHANGE_ALL_PROF_2 } from '../defs/S_PLAYER_CHANGE_ALL_PROF_2';
import { S_PLAYER_CHANGE_EXP_2 } from '../defs/S_PLAYER_CHANGE_EXP_2';
import { S_PLAYER_CHANGE_PROF_2 } from '../defs/S_PLAYER_CHANGE_PROF_2';
import { S_PREMIUM_SLOT_DATALIST_2 } from '../defs/S_PREMIUM_SLOT_DATALIST_2';
import { S_PRIVATE_CHANNEL_NOTICE_2 } from '../defs/S_PRIVATE_CHANNEL_NOTICE_2';
import { S_QUEST_INFO_2 } from '../defs/S_QUEST_INFO_2';
import { S_REQUEST_PRIVATE_CHANNEL_INFO_2 } from '../defs/S_REQUEST_PRIVATE_CHANNEL_INFO_2';
import { S_RESULT_EVENT_SEED_2 } from '../defs/S_RESULT_EVENT_SEED_2';
import { S_SHORTCUT_CHANGE_2 } from '../defs/S_SHORTCUT_CHANGE_2';
import { S_SKILL_LIST_2 } from '../defs/S_SKILL_LIST_2';
import { S_SPAWN_BONFIRE_2 } from '../defs/S_SPAWN_BONFIRE_2';
import { S_SPAWN_BUILD_OBJECT_2 } from '../defs/S_SPAWN_BUILD_OBJECT_2';
import { S_SPAWN_EVENT_SEED_2 } from '../defs/S_SPAWN_EVENT_SEED_2';
import { S_STICK_TO_USER_END_2 } from '../defs/S_STICK_TO_USER_END_2';
import { S_TARGET_INFO_2 } from '../defs/S_TARGET_INFO_2';
import { S_TRADE_BROKER_HISTORY_ITEM_LIST_2 } from '../defs/S_TRADE_BROKER_HISTORY_ITEM_LIST_2';
import { S_UNMOUNT_VEHICLE_2 } from '../defs/S_UNMOUNT_VEHICLE_2';
import { S_USER_BLOCK_LIST_2 } from '../defs/S_USER_BLOCK_LIST_2';
import { S_USER_CHANGE_FACE_CUSTOM_2 } from '../defs/S_USER_CHANGE_FACE_CUSTOM_2';
import { S_USER_LEVELUP_2 } from '../defs/S_USER_LEVELUP_2';
import { S_USER_LOCATION_IN_ACTION_2 } from '../defs/S_USER_LOCATION_IN_ACTION_2';
import { S_USER_WEAPON_APPEARANCE_CHANGE_2 } from '../defs/S_USER_WEAPON_APPEARANCE_CHANGE_2';
import { S_VIEW_WARE_EX_2 } from '../defs/S_VIEW_WARE_EX_2';
import { C_CANCEL_SKILL_3 } from '../defs/C_CANCEL_SKILL_3';
import { C_CAN_LOCKON_TARGET_3 } from '../defs/C_CAN_LOCKON_TARGET_3';
import { C_DEL_ITEM_3 } from '../defs/C_DEL_ITEM_3';
import { C_NOTIMELINE_SKILL_3 } from '../defs/C_NOTIMELINE_SKILL_3';
import { C_PUT_WARE_ITEM_3 } from '../defs/C_PUT_WARE_ITEM_3';
import { C_SHOW_ITEM_TOOLTIP_EX_3 } from '../defs/C_SHOW_ITEM_TOOLTIP_EX_3';
import { C_USE_ITEM_3 } from '../defs/C_USE_ITEM_3';
import { S_ABNORMALITY_BEGIN_4 } from '../defs/S_ABNORMALITY_BEGIN_4';
import { S_ACCOUNT_PACKAGE_LIST_3 } from '../defs/S_ACCOUNT_PACKAGE_LIST_3';
import { S_APPLY_TITLE_3 } from '../defs/S_APPLY_TITLE_3';
import { S_BOSS_GAGE_INFO_3 } from '../defs/S_BOSS_GAGE_INFO_3';
import { S_CAN_LOCKON_TARGET_3 } from '../defs/S_CAN_LOCKON_TARGET_3';
import { S_CHAT_3 } from '../defs/S_CHAT_3';
import { S_CONNECT_SKILL_ARROW_3 } from '../defs/S_CONNECT_SKILL_ARROW_3';
import { S_CREATURE_LIFE_3 } from '../defs/S_CREATURE_LIFE_3';
import { S_DECREASE_COOLTIME_SKILL_3 } from '../defs/S_DECREASE_COOLTIME_SKILL_3';
import { S_DEFEND_SUCCESS_3 } from '../defs/S_DEFEND_SUCCESS_3';
import { S_DESPAWN_NPC_3 } from '../defs/S_DESPAWN_NPC_3';
import { S_DESPAWN_USER_3 } from '../defs/S_DESPAWN_USER_3';
import { S_DIALOG_3 } from '../defs/S_DIALOG_3';
import { S_EXIT_3 } from '../defs/S_EXIT_3';
import { S_FONT_SWAP_INFO_3 } from '../defs/S_FONT_SWAP_INFO_3';
import { S_GRANT_SKILL_3 } from '../defs/S_GRANT_SKILL_3';
import { S_INSTANT_DASH_3 } from '../defs/S_INSTANT_DASH_3';
import { S_INSTANT_MOVE_3 } from '../defs/S_INSTANT_MOVE_3';
import { S_ITEMLIST_3 } from '../defs/S_ITEMLIST_3';
import { S_LOAD_TOPO_3 } from '../defs/S_LOAD_TOPO_3';
import { S_NPC_LOCATION_3 } from '../defs/S_NPC_LOCATION_3';
import { S_PARTY_MEMBER_ABNORMAL_ADD_3 } from '../defs/S_PARTY_MEMBER_ABNORMAL_ADD_3';
import { S_PARTY_MEMBER_ABNORMAL_REFRESH_3 } from '../defs/S_PARTY_MEMBER_ABNORMAL_REFRESH_3';
import { S_PARTY_MEMBER_INTERVAL_POS_UPDATE_3 } from '../defs/S_PARTY_MEMBER_INTERVAL_POS_UPDATE_3';
import { S_PARTY_MEMBER_STAT_UPDATE_3 } from '../defs/S_PARTY_MEMBER_STAT_UPDATE_3';
import { S_REGISTER_ENCHANT_ITEM_3 } from '../defs/S_REGISTER_ENCHANT_ITEM_3';
import { S_REGISTER_EVOLUTION_ITEM_3 } from '../defs/S_REGISTER_EVOLUTION_ITEM_3';
import { S_REQUEST_SERVANT_INFO_LIST_3 } from '../defs/S_REQUEST_SERVANT_INFO_LIST_3';
import { S_SHOW_HP_3 } from '../defs/S_SHOW_HP_3';
import { S_SKILL_CATEGORY_3 } from '../defs/S_SKILL_CATEGORY_3';
import { S_SPAWN_DOOR_3 } from '../defs/S_SPAWN_DOOR_3';
import { S_SPAWN_ME_3 } from '../defs/S_SPAWN_ME_3';
import { S_SPAWN_SHUTTLE_3 } from '../defs/S_SPAWN_SHUTTLE_3';
import { S_SPAWN_WORKOBJECT_3 } from '../defs/S_SPAWN_WORKOBJECT_3';
import { S_START_ACTION_SCRIPT_3 } from '../defs/S_START_ACTION_SCRIPT_3';
import { S_START_CHANGE_USER_APPEARANCE_3 } from '../defs/S_START_CHANGE_USER_APPEARANCE_3';
import { S_START_COOLTIME_SKILL_3 } from '../defs/S_START_COOLTIME_SKILL_3';
import { S_START_PRODUCE_3 } from '../defs/S_START_PRODUCE_3';
import { S_USER_STATUS_3 } from '../defs/S_USER_STATUS_3';
import { S_WHISPER_3 } from '../defs/S_WHISPER_3';
import { C_HIT_USER_PROJECTILE_4 } from '../defs/C_HIT_USER_PROJECTILE_4';
import { C_NOTIFY_LOCATION_IN_ACTION_4 } from '../defs/C_NOTIFY_LOCATION_IN_ACTION_4';
import { C_NOTIFY_LOCATION_IN_DASH_4 } from '../defs/C_NOTIFY_LOCATION_IN_DASH_4';
import { C_PLAYER_FLYING_LOCATION_4 } from '../defs/C_PLAYER_FLYING_LOCATION_4';
import { C_PRESS_SKILL_4 } from '../defs/C_PRESS_SKILL_4';
import { C_TRY_LOOT_DROPITEM_4 } from '../defs/C_TRY_LOOT_DROPITEM_4';
import { S_CANNOT_START_SKILL_4 } from '../defs/S_CANNOT_START_SKILL_4';
import { S_DESPAWN_DROPITEM_4 } from '../defs/S_DESPAWN_DROPITEM_4';
import { S_END_USER_PROJECTILE_4 } from '../defs/S_END_USER_PROJECTILE_4';
import { S_INSTANCE_ARROW_4 } from '../defs/S_INSTANCE_ARROW_4';
import { S_PARTY_MEMBER_CHANGE_HP_4 } from '../defs/S_PARTY_MEMBER_CHANGE_HP_4';
import { S_REQUEST_SPAWN_SERVANT_4 } from '../defs/S_REQUEST_SPAWN_SERVANT_4';
import { S_SPAWN_COLLECTION_4 } from '../defs/S_SPAWN_COLLECTION_4';
import { S_START_CLIENT_CUSTOM_SKILL_4 } from '../defs/S_START_CLIENT_CUSTOM_SKILL_4';
import { S_START_INVERSE_CAPTURE_4 } from '../defs/S_START_INVERSE_CAPTURE_4';
import { S_UPDATE_EVENT_SEED_STATE_4 } from '../defs/S_UPDATE_EVENT_SEED_STATE_4';
import { C_PLAYER_LOCATION_5 } from '../defs/C_PLAYER_LOCATION_5';
import { C_START_INSTANCE_SKILL_EX_5 } from '../defs/C_START_INSTANCE_SKILL_EX_5';
import { S_ACTION_END_5 } from '../defs/S_ACTION_END_5';
import { S_SPAWN_PROJECTILE_5 } from '../defs/S_SPAWN_PROJECTILE_5';
import { S_USER_LOCATION_5 } from '../defs/S_USER_LOCATION_5';
import { C_START_COMBO_INSTANT_SKILL_6 } from '../defs/C_START_COMBO_INSTANT_SKILL_6';
import { S_CREATURE_CHANGE_HP_6 } from '../defs/S_CREATURE_CHANGE_HP_6';
import { S_UNICAST_TRANSFORM_DATA_6 } from '../defs/S_UNICAST_TRANSFORM_DATA_6';
import { C_START_INSTANCE_SKILL_7 } from '../defs/C_START_INSTANCE_SKILL_7';
import { C_START_SKILL_7 } from '../defs/C_START_SKILL_7';
import { C_START_TARGETED_SKILL_7 } from '../defs/C_START_TARGETED_SKILL_7';
import { S_PARTY_MEMBER_LIST_7 } from '../defs/S_PARTY_MEMBER_LIST_7';
import { S_USER_EXTERNAL_CHANGE_7 } from '../defs/S_USER_EXTERNAL_CHANGE_7';
import { S_SPAWN_DROPITEM_8 } from '../defs/S_SPAWN_DROPITEM_8';
import { S_ACTION_STAGE_9 } from '../defs/S_ACTION_STAGE_9';
import { S_START_USER_PROJECTILE_9 } from '../defs/S_START_USER_PROJECTILE_9';
import { S_SPAWN_NPC_11 } from '../defs/S_SPAWN_NPC_11';
import { S_USER_PAPERDOLL_INFO_11 } from '../defs/S_USER_PAPERDOLL_INFO_11';
import { S_EACH_SKILL_RESULT_14 } from '../defs/S_EACH_SKILL_RESULT_14';
import { S_LOGIN_14 } from '../defs/S_LOGIN_14';
import { S_PLAYER_STAT_UPDATE_14 } from '../defs/S_PLAYER_STAT_UPDATE_14';
import { S_SHOW_ITEM_TOOLTIP_14 } from '../defs/S_SHOW_ITEM_TOOLTIP_14';
import { S_SPAWN_USER_15 } from '../defs/S_SPAWN_USER_15';
import { S_GET_USER_LIST_17 } from '../defs/S_GET_USER_LIST_17';

type CallbackFunction<PacketT> = (event: PacketT, fake?: boolean) => boolean | void;
export interface HookOptions { order?: number, filter?: { fake?: boolean, incoming?: boolean, modified?: boolean, silenced?: boolean } }

export interface Mod {
hook(packet: '*', version: 'raw', options?: HookOptions, cb?: (event: any, fake?: boolean) => boolean | void);
  hook(packet: 'C_ADD_FRIEND', version: 1 | '*', options?: HookOptions | CallbackFunction<C_ADD_FRIEND_1>, cb?: CallbackFunction<C_ADD_FRIEND_1>);
  hook(packet: 'C_ADD_TELEPORT_TO_POS_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_ADD_TELEPORT_TO_POS_LIST_1>, cb?: CallbackFunction<C_ADD_TELEPORT_TO_POS_LIST_1>);
  hook(packet: 'C_ADMIN', version: 1 | '*', options?: HookOptions | CallbackFunction<C_ADMIN_1>, cb?: CallbackFunction<C_ADMIN_1>);
  hook(packet: 'C_APPLY_PARTY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_APPLY_PARTY_1>, cb?: CallbackFunction<C_APPLY_PARTY_1>);
  hook(packet: 'C_ASK_INTERACTIVE', version: 2 | '*', options?: HookOptions | CallbackFunction<C_ASK_INTERACTIVE_2>, cb?: CallbackFunction<C_ASK_INTERACTIVE_2>);
  hook(packet: 'C_BAN_PARTY_MEMBER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_BAN_PARTY_MEMBER_1>, cb?: CallbackFunction<C_BAN_PARTY_MEMBER_1>);
  hook(packet: 'C_BIND_ITEM_BEGIN_PROGRESS', version: 1 | '*', options?: HookOptions | CallbackFunction<C_BIND_ITEM_BEGIN_PROGRESS_1>, cb?: CallbackFunction<C_BIND_ITEM_BEGIN_PROGRESS_1>);
  hook(packet: 'C_BIND_ITEM_EXECUTE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_BIND_ITEM_EXECUTE_1>, cb?: CallbackFunction<C_BIND_ITEM_EXECUTE_1>);
  hook(packet: 'C_BLOCK_USER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_BLOCK_USER_1>, cb?: CallbackFunction<C_BLOCK_USER_1>);
  hook(packet: 'C_CANCEL_CHANGE_USER_APPEARANCE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CANCEL_CHANGE_USER_APPEARANCE_1>, cb?: CallbackFunction<C_CANCEL_CHANGE_USER_APPEARANCE_1>);
  hook(packet: 'C_CANCEL_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CANCEL_CONTRACT_1>, cb?: CallbackFunction<C_CANCEL_CONTRACT_1>);
  hook(packet: 'C_CHANGE_PARTY_MEMBER_AUTHORITY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CHANGE_PARTY_MEMBER_AUTHORITY_1>, cb?: CallbackFunction<C_CHANGE_PARTY_MEMBER_AUTHORITY_1>);
  hook(packet: 'C_CHAT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CHAT_1>, cb?: CallbackFunction<C_CHAT_1>);
  hook(packet: 'C_CHECK_VERSION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CHECK_VERSION_1>, cb?: CallbackFunction<C_CHECK_VERSION_1>);
  hook(packet: 'C_COMPLETE_DAILY_EVENT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_COMPLETE_DAILY_EVENT_1>, cb?: CallbackFunction<C_COMPLETE_DAILY_EVENT_1>);
  hook(packet: 'C_COMPLETE_EXTRA_EVENT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_COMPLETE_EXTRA_EVENT_1>, cb?: CallbackFunction<C_COMPLETE_EXTRA_EVENT_1>);
  hook(packet: 'C_CONFIRM_UPDATE_NOTIFICATION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_CONFIRM_UPDATE_NOTIFICATION_1>, cb?: CallbackFunction<C_CONFIRM_UPDATE_NOTIFICATION_1>);
  hook(packet: 'C_DELETE_FRIEND', version: 1 | '*', options?: HookOptions | CallbackFunction<C_DELETE_FRIEND_1>, cb?: CallbackFunction<C_DELETE_FRIEND_1>);
  hook(packet: 'C_DELETE_TELEPORT_TO_POS_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_DELETE_TELEPORT_TO_POS_LIST_1>, cb?: CallbackFunction<C_DELETE_TELEPORT_TO_POS_LIST_1>);
  hook(packet: 'C_DIALOG', version: 1 | '*', options?: HookOptions | CallbackFunction<C_DIALOG_1>, cb?: CallbackFunction<C_DIALOG_1>);
  hook(packet: 'C_DISMISS_PARTY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_DISMISS_PARTY_1>, cb?: CallbackFunction<C_DISMISS_PARTY_1>);
  hook(packet: 'C_EDIT_BLOCKED_USER_MEMO', version: 1 | '*', options?: HookOptions | CallbackFunction<C_EDIT_BLOCKED_USER_MEMO_1>, cb?: CallbackFunction<C_EDIT_BLOCKED_USER_MEMO_1>);
  hook(packet: 'C_END_MOVIE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_END_MOVIE_1>, cb?: CallbackFunction<C_END_MOVIE_1>);
  hook(packet: 'C_GACHA_CANCEL', version: 1 | '*', options?: HookOptions | CallbackFunction<C_GACHA_CANCEL_1>, cb?: CallbackFunction<C_GACHA_CANCEL_1>);
  hook(packet: 'C_GACHA_TRY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_GACHA_TRY_1>, cb?: CallbackFunction<C_GACHA_TRY_1>);
  hook(packet: 'C_GET_IN_SHUTTLE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_GET_IN_SHUTTLE_1>, cb?: CallbackFunction<C_GET_IN_SHUTTLE_1>);
  hook(packet: 'C_GET_OUT_SHUTTLE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_GET_OUT_SHUTTLE_1>, cb?: CallbackFunction<C_GET_OUT_SHUTTLE_1>);
  hook(packet: 'C_GET_USER_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_GET_USER_LIST_1>, cb?: CallbackFunction<C_GET_USER_LIST_1>);
  hook(packet: 'C_INVITE_USER_TO_GUILD', version: 1 | '*', options?: HookOptions | CallbackFunction<C_INVITE_USER_TO_GUILD_1>, cb?: CallbackFunction<C_INVITE_USER_TO_GUILD_1>);
  hook(packet: 'C_ITEM_COLORING_SET_COLOR', version: 2 | '*', options?: HookOptions | CallbackFunction<C_ITEM_COLORING_SET_COLOR_2>, cb?: CallbackFunction<C_ITEM_COLORING_SET_COLOR_2>);
  hook(packet: 'C_LEAVE_PARTY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_LEAVE_PARTY_1>, cb?: CallbackFunction<C_LEAVE_PARTY_1>);
  hook(packet: 'C_LEAVE_PRIVATE_CHANNEL', version: 1 | '*', options?: HookOptions | CallbackFunction<C_LEAVE_PRIVATE_CHANNEL_1>, cb?: CallbackFunction<C_LEAVE_PRIVATE_CHANNEL_1>);
  hook(packet: 'C_LOAD_TOPO_FIN', version: 1 | '*', options?: HookOptions | CallbackFunction<C_LOAD_TOPO_FIN_1>, cb?: CallbackFunction<C_LOAD_TOPO_FIN_1>);
  hook(packet: 'C_MERGE_ITEM_EXECUTE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_MERGE_ITEM_EXECUTE_1>, cb?: CallbackFunction<C_MERGE_ITEM_EXECUTE_1>);
  hook(packet: 'C_OP_COMMAND', version: 1 | '*', options?: HookOptions | CallbackFunction<C_OP_COMMAND_1>, cb?: CallbackFunction<C_OP_COMMAND_1>);
  hook(packet: 'C_PARTY_APPLICATION_DENIED', version: 1 | '*', options?: HookOptions | CallbackFunction<C_PARTY_APPLICATION_DENIED_1>, cb?: CallbackFunction<C_PARTY_APPLICATION_DENIED_1>);
  hook(packet: 'C_PARTY_MARKER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_PARTY_MARKER_1>, cb?: CallbackFunction<C_PARTY_MARKER_1>);
  hook(packet: 'C_PARTY_MATCH_WINDOW_CLOSED', version: 1 | '*', options?: HookOptions | CallbackFunction<C_PARTY_MATCH_WINDOW_CLOSED_1>, cb?: CallbackFunction<C_PARTY_MATCH_WINDOW_CLOSED_1>);
  hook(packet: 'C_REGISTER_ENCHANT_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REGISTER_ENCHANT_ITEM_1>, cb?: CallbackFunction<C_REGISTER_ENCHANT_ITEM_1>);
  hook(packet: 'C_REGISTER_EVOLUTION_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REGISTER_EVOLUTION_ITEM_1>, cb?: CallbackFunction<C_REGISTER_EVOLUTION_ITEM_1>);
  hook(packet: 'C_REGISTER_PARTY_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REGISTER_PARTY_INFO_1>, cb?: CallbackFunction<C_REGISTER_PARTY_INFO_1>);
  hook(packet: 'C_REMOVE_BLOCKED_USER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REMOVE_BLOCKED_USER_1>, cb?: CallbackFunction<C_REMOVE_BLOCKED_USER_1>);
  hook(packet: 'C_REPLY_THROUGH_ARBITER_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REPLY_THROUGH_ARBITER_CONTRACT_1>, cb?: CallbackFunction<C_REPLY_THROUGH_ARBITER_CONTRACT_1>);
  hook(packet: 'C_REQUEST_ABNORMALITY_TOOLTIP_VALUE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_ABNORMALITY_TOOLTIP_VALUE_1>, cb?: CallbackFunction<C_REQUEST_ABNORMALITY_TOOLTIP_VALUE_1>);
  hook(packet: 'C_REQUEST_CANDIDATE_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_CANDIDATE_LIST_1>, cb?: CallbackFunction<C_REQUEST_CANDIDATE_LIST_1>);
  hook(packet: 'C_REQUEST_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_CONTRACT_1>, cb?: CallbackFunction<C_REQUEST_CONTRACT_1>);
  hook(packet: 'C_REQUEST_ENCHANT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_ENCHANT_1>, cb?: CallbackFunction<C_REQUEST_ENCHANT_1>);
  hook(packet: 'C_REQUEST_EVOLUTION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_EVOLUTION_1>, cb?: CallbackFunction<C_REQUEST_EVOLUTION_1>);
  hook(packet: 'C_REQUEST_GAMESTAT_PING', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_GAMESTAT_PING_1>, cb?: CallbackFunction<C_REQUEST_GAMESTAT_PING_1>);
  hook(packet: 'C_REQUEST_NONDB_ITEM_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_NONDB_ITEM_INFO_2>, cb?: CallbackFunction<C_REQUEST_NONDB_ITEM_INFO_2>);
  hook(packet: 'C_REQUEST_PARTY_MATCH_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_PARTY_MATCH_INFO_1>, cb?: CallbackFunction<C_REQUEST_PARTY_MATCH_INFO_1>);
  hook(packet: 'C_REQUEST_PARTY_MATCH_INFO_PAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_PARTY_MATCH_INFO_PAGE_1>, cb?: CallbackFunction<C_REQUEST_PARTY_MATCH_INFO_PAGE_1>);
  hook(packet: 'C_REQUEST_PARTY_MATCH_LINK', version: 1 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_PARTY_MATCH_LINK_1>, cb?: CallbackFunction<C_REQUEST_PARTY_MATCH_LINK_1>);
  hook(packet: 'C_RESET_ALL_DUNGEON', version: 1 | '*', options?: HookOptions | CallbackFunction<C_RESET_ALL_DUNGEON_1>, cb?: CallbackFunction<C_RESET_ALL_DUNGEON_1>);
  hook(packet: 'C_RETURN_TO_LOBBY', version: 1 | '*', options?: HookOptions | CallbackFunction<C_RETURN_TO_LOBBY_1>, cb?: CallbackFunction<C_RETURN_TO_LOBBY_1>);
  hook(packet: 'C_RQ_COMMIT_DECOMPOSITION_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_RQ_COMMIT_DECOMPOSITION_CONTRACT_1>, cb?: CallbackFunction<C_RQ_COMMIT_DECOMPOSITION_CONTRACT_1>);
  hook(packet: 'C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION_1>, cb?: CallbackFunction<C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION_1>);
  hook(packet: 'C_SAVE_CLIENT_ACCOUNT_SETTING', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SAVE_CLIENT_ACCOUNT_SETTING_1>, cb?: CallbackFunction<C_SAVE_CLIENT_ACCOUNT_SETTING_1>);
  hook(packet: 'C_SECOND_PASSWORD_AUTH', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SECOND_PASSWORD_AUTH_1>, cb?: CallbackFunction<C_SECOND_PASSWORD_AUTH_1>);
  hook(packet: 'C_SELECT_USER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SELECT_USER_1>, cb?: CallbackFunction<C_SELECT_USER_1>);
  hook(packet: 'C_SET_VISIBLE_RANGE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SET_VISIBLE_RANGE_1>, cb?: CallbackFunction<C_SET_VISIBLE_RANGE_1>);
  hook(packet: 'C_SHOW_ITEMLIST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SHOW_ITEMLIST_1>, cb?: CallbackFunction<C_SHOW_ITEMLIST_1>);
  hook(packet: 'C_SOCIAL', version: 1 | '*', options?: HookOptions | CallbackFunction<C_SOCIAL_1>, cb?: CallbackFunction<C_SOCIAL_1>);
  hook(packet: 'C_START_ENCHANT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_START_ENCHANT_1>, cb?: CallbackFunction<C_START_ENCHANT_1>);
  hook(packet: 'C_START_EVOLUTION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_START_EVOLUTION_1>, cb?: CallbackFunction<C_START_EVOLUTION_1>);
  hook(packet: 'C_START_PRODUCE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_START_PRODUCE_1>, cb?: CallbackFunction<C_START_PRODUCE_1>);
  hook(packet: 'C_TELEPORT_TO_POS', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TELEPORT_TO_POS_1>, cb?: CallbackFunction<C_TELEPORT_TO_POS_1>);
  hook(packet: 'C_TELEPORT_TO_VILLAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TELEPORT_TO_VILLAGE_1>, cb?: CallbackFunction<C_TELEPORT_TO_VILLAGE_1>);
  hook(packet: 'C_TRADE_BROKER_DEAL_CONFIRM', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_DEAL_CONFIRM_1>, cb?: CallbackFunction<C_TRADE_BROKER_DEAL_CONFIRM_1>);
  hook(packet: 'C_TRADE_BROKER_REJECT_SUGGEST', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_REJECT_SUGGEST_1>, cb?: CallbackFunction<C_TRADE_BROKER_REJECT_SUGGEST_1>);
  hook(packet: 'C_TRADE_BROKER_SUGGEST_DEAL', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_SUGGEST_DEAL_1>, cb?: CallbackFunction<C_TRADE_BROKER_SUGGEST_DEAL_1>);
  hook(packet: 'C_TRADE_BROKER_WAITING_ITEM_LIST_NEW', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_WAITING_ITEM_LIST_NEW_1>, cb?: CallbackFunction<C_TRADE_BROKER_WAITING_ITEM_LIST_NEW_1>);
  hook(packet: 'C_TRADE_BROKER_WAITING_ITEM_LIST_PAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_WAITING_ITEM_LIST_PAGE_1>, cb?: CallbackFunction<C_TRADE_BROKER_WAITING_ITEM_LIST_PAGE_1>);
  hook(packet: 'C_UNMOUNT_VEHICLE', version: 1 | '*', options?: HookOptions | CallbackFunction<C_UNMOUNT_VEHICLE_1>, cb?: CallbackFunction<C_UNMOUNT_VEHICLE_1>);
  hook(packet: 'C_UNREGISTER_ENCHANT_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<C_UNREGISTER_ENCHANT_ITEM_1>, cb?: CallbackFunction<C_UNREGISTER_ENCHANT_ITEM_1>);
  hook(packet: 'C_UNREGISTER_EVOLUTION_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<C_UNREGISTER_EVOLUTION_ITEM_1>, cb?: CallbackFunction<C_UNREGISTER_EVOLUTION_ITEM_1>);
  hook(packet: 'C_UNREGISTER_PARTY_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<C_UNREGISTER_PARTY_INFO_1>, cb?: CallbackFunction<C_UNREGISTER_PARTY_INFO_1>);
  hook(packet: 'C_UPDATE_REACTION_POS', version: 1 | '*', options?: HookOptions | CallbackFunction<C_UPDATE_REACTION_POS_1>, cb?: CallbackFunction<C_UPDATE_REACTION_POS_1>);
  hook(packet: 'C_USE_PREMIUM_SLOT', version: 1 | '*', options?: HookOptions | CallbackFunction<C_USE_PREMIUM_SLOT_1>, cb?: CallbackFunction<C_USE_PREMIUM_SLOT_1>);
  hook(packet: 'C_VISIT_NEW_SECTION', version: 1 | '*', options?: HookOptions | CallbackFunction<C_VISIT_NEW_SECTION_1>, cb?: CallbackFunction<C_VISIT_NEW_SECTION_1>);
  hook(packet: 'C_WHISPER', version: 1 | '*', options?: HookOptions | CallbackFunction<C_WHISPER_1>, cb?: CallbackFunction<C_WHISPER_1>);
  hook(packet: 'S_ABNORMALITY_DAMAGE_ABSORB', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_DAMAGE_ABSORB_1>, cb?: CallbackFunction<S_ABNORMALITY_DAMAGE_ABSORB_1>);
  hook(packet: 'S_ABNORMALITY_END', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_END_1>, cb?: CallbackFunction<S_ABNORMALITY_END_1>);
  hook(packet: 'S_ABNORMALITY_REFRESH', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_REFRESH_2>, cb?: CallbackFunction<S_ABNORMALITY_REFRESH_2>);
  hook(packet: 'S_ABNORMALITY_RESIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_RESIST_1>, cb?: CallbackFunction<S_ABNORMALITY_RESIST_1>);
  hook(packet: 'S_ABNORMALITY_TOOLTIP_VALUE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_TOOLTIP_VALUE_1>, cb?: CallbackFunction<S_ABNORMALITY_TOOLTIP_VALUE_1>);
  hook(packet: 'S_ACCEPT_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ACCEPT_CONTRACT_1>, cb?: CallbackFunction<S_ACCEPT_CONTRACT_1>);
  hook(packet: 'S_ADD_INTER_PARTY_MATCH_POOL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ADD_INTER_PARTY_MATCH_POOL_1>, cb?: CallbackFunction<S_ADD_INTER_PARTY_MATCH_POOL_1>);
  hook(packet: 'S_AERO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_AERO_1>, cb?: CallbackFunction<S_AERO_1>);
  hook(packet: 'S_AIR_REACTION_END', version: 1 | '*', options?: HookOptions | CallbackFunction<S_AIR_REACTION_END_1>, cb?: CallbackFunction<S_AIR_REACTION_END_1>);
  hook(packet: 'S_ANNOUNCE_UPDATE_NOTIFICATION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ANNOUNCE_UPDATE_NOTIFICATION_1>, cb?: CallbackFunction<S_ANNOUNCE_UPDATE_NOTIFICATION_1>);
  hook(packet: 'S_ASK_BIDDING_RARE_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ASK_BIDDING_RARE_ITEM_1>, cb?: CallbackFunction<S_ASK_BIDDING_RARE_ITEM_1>);
  hook(packet: 'S_ASK_TELEPORT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ASK_TELEPORT_1>, cb?: CallbackFunction<S_ASK_TELEPORT_1>);
  hook(packet: 'S_AVAILABLE_EVENT_MATCHING_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_AVAILABLE_EVENT_MATCHING_LIST_2>, cb?: CallbackFunction<S_AVAILABLE_EVENT_MATCHING_LIST_2>);
  hook(packet: 'S_BAN_PARTY_MEMBER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_BAN_PARTY_MEMBER_1>, cb?: CallbackFunction<S_BAN_PARTY_MEMBER_1>);
  hook(packet: 'S_BATTLE_FIELD_ENTRANCE_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_BATTLE_FIELD_ENTRANCE_INFO_1>, cb?: CallbackFunction<S_BATTLE_FIELD_ENTRANCE_INFO_1>);
  hook(packet: 'S_BATTLE_FIELD_POINT_STORE_SELL_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_BATTLE_FIELD_POINT_STORE_SELL_LIST_1>, cb?: CallbackFunction<S_BATTLE_FIELD_POINT_STORE_SELL_LIST_1>);
  hook(packet: 'S_BEGIN_THROUGH_ARBITER_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_BEGIN_THROUGH_ARBITER_CONTRACT_1>, cb?: CallbackFunction<S_BEGIN_THROUGH_ARBITER_CONTRACT_1>);
  hook(packet: 'S_CANCEL_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CANCEL_CONTRACT_1>, cb?: CallbackFunction<S_CANCEL_CONTRACT_1>);
  hook(packet: 'S_CHANGE_EP_EXP_DAILY_LIMIT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_EP_EXP_DAILY_LIMIT_1>, cb?: CallbackFunction<S_CHANGE_EP_EXP_DAILY_LIMIT_1>);
  hook(packet: 'S_CHANGE_EP_POINT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_EP_POINT_1>, cb?: CallbackFunction<S_CHANGE_EP_POINT_1>);
  hook(packet: 'S_CHANGE_FRIEND_STATE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_FRIEND_STATE_1>, cb?: CallbackFunction<S_CHANGE_FRIEND_STATE_1>);
  hook(packet: 'S_CHANGE_GUILD_CHIEF', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_GUILD_CHIEF_1>, cb?: CallbackFunction<S_CHANGE_GUILD_CHIEF_1>);
  hook(packet: 'S_CHANGE_VOICE_USE_QAC', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_VOICE_USE_QAC_1>, cb?: CallbackFunction<S_CHANGE_VOICE_USE_QAC_1>);
  hook(packet: 'S_CHECK_VERSION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CHECK_VERSION_1>, cb?: CallbackFunction<S_CHECK_VERSION_1>);
  hook(packet: 'S_CLEAR_ALL_HOLDED_ABNORMALITY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CLEAR_ALL_HOLDED_ABNORMALITY_1>, cb?: CallbackFunction<S_CLEAR_ALL_HOLDED_ABNORMALITY_1>);
  hook(packet: 'S_COMPLETE_EVENT_MATCHING_QUEST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_COMPLETE_EVENT_MATCHING_QUEST_1>, cb?: CallbackFunction<S_COMPLETE_EVENT_MATCHING_QUEST_1>);
  hook(packet: 'S_CUSTOM_STYLE_SYSTEM_MESSAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_CUSTOM_STYLE_SYSTEM_MESSAGE_1>, cb?: CallbackFunction<S_CUSTOM_STYLE_SYSTEM_MESSAGE_1>);
  hook(packet: 'S_DELETE_FRIEND', version: 1 | '*', options?: HookOptions | CallbackFunction<S_DELETE_FRIEND_1>, cb?: CallbackFunction<S_DELETE_FRIEND_1>);
  hook(packet: 'S_DESPAWN_EVENT_SEED', version: 1 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_EVENT_SEED_1>, cb?: CallbackFunction<S_DESPAWN_EVENT_SEED_1>);
  hook(packet: 'S_DESPAWN_PROJECTILE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_PROJECTILE_2>, cb?: CallbackFunction<S_DESPAWN_PROJECTILE_2>);
  hook(packet: 'S_DESTROY_GUILD_TOWER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_DESTROY_GUILD_TOWER_1>, cb?: CallbackFunction<S_DESTROY_GUILD_TOWER_1>);
  hook(packet: 'S_DUNGEON_CAMERA_SET', version: 1 | '*', options?: HookOptions | CallbackFunction<S_DUNGEON_CAMERA_SET_1>, cb?: CallbackFunction<S_DUNGEON_CAMERA_SET_1>);
  hook(packet: 'S_DUNGEON_CLEAR_COUNT_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_DUNGEON_CLEAR_COUNT_LIST_1>, cb?: CallbackFunction<S_DUNGEON_CLEAR_COUNT_LIST_1>);
  hook(packet: 'S_END_CHANGE_USER_APPEARANCE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_END_CHANGE_USER_APPEARANCE_1>, cb?: CallbackFunction<S_END_CHANGE_USER_APPEARANCE_1>);
  hook(packet: 'S_END_PRODUCE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_END_PRODUCE_1>, cb?: CallbackFunction<S_END_PRODUCE_1>);
  hook(packet: 'S_EP_SYSTEM_DAILY_EVENT_EXP_ON_OFF', version: 1 | '*', options?: HookOptions | CallbackFunction<S_EP_SYSTEM_DAILY_EVENT_EXP_ON_OFF_1>, cb?: CallbackFunction<S_EP_SYSTEM_DAILY_EVENT_EXP_ON_OFF_1>);
  hook(packet: 'S_F2P_PremiumUser_Permission', version: 1 | '*', options?: HookOptions | CallbackFunction<S_F2P_PremiumUser_Permission_1>, cb?: CallbackFunction<S_F2P_PremiumUser_Permission_1>);
  hook(packet: 'S_FACIAL_ATTACHMENT_BROADCAST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_FACIAL_ATTACHMENT_BROADCAST_1>, cb?: CallbackFunction<S_FACIAL_ATTACHMENT_BROADCAST_1>);
  hook(packet: 'S_FIELD_EVENT_PROGRESS_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_FIELD_EVENT_PROGRESS_INFO_1>, cb?: CallbackFunction<S_FIELD_EVENT_PROGRESS_INFO_1>);
  hook(packet: 'S_FIN_INTER_PARTY_MATCH', version: 1 | '*', options?: HookOptions | CallbackFunction<S_FIN_INTER_PARTY_MATCH_1>, cb?: CallbackFunction<S_FIN_INTER_PARTY_MATCH_1>);
  hook(packet: 'S_FIX_VEHICLE_PROGRESS', version: 1 | '*', options?: HookOptions | CallbackFunction<S_FIX_VEHICLE_PROGRESS_1>, cb?: CallbackFunction<S_FIX_VEHICLE_PROGRESS_1>);
  hook(packet: 'S_FRIEND_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_FRIEND_LIST_1>, cb?: CallbackFunction<S_FRIEND_LIST_1>);
  hook(packet: 'S_GET_IN_SHUTTLE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GET_IN_SHUTTLE_1>, cb?: CallbackFunction<S_GET_IN_SHUTTLE_1>);
  hook(packet: 'S_GET_OUT_SHUTTLE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GET_OUT_SHUTTLE_1>, cb?: CallbackFunction<S_GET_OUT_SHUTTLE_1>);
  hook(packet: 'S_GET_USER_GUILD_LOGO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GET_USER_GUILD_LOGO_1>, cb?: CallbackFunction<S_GET_USER_GUILD_LOGO_1>);
  hook(packet: 'S_GMEVENT_GUIDE_MESSAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GMEVENT_GUIDE_MESSAGE_1>, cb?: CallbackFunction<S_GMEVENT_GUIDE_MESSAGE_1>);
  hook(packet: 'S_GMEVENT_OX_QUIZ_OPEN', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GMEVENT_OX_QUIZ_OPEN_1>, cb?: CallbackFunction<S_GMEVENT_OX_QUIZ_OPEN_1>);
  hook(packet: 'S_GMEVENT_OX_QUIZ_RESULT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GMEVENT_OX_QUIZ_RESULT_1>, cb?: CallbackFunction<S_GMEVENT_OX_QUIZ_RESULT_1>);
  hook(packet: 'S_GROUP_NPC_LOCATION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GROUP_NPC_LOCATION_1>, cb?: CallbackFunction<S_GROUP_NPC_LOCATION_1>);
  hook(packet: 'S_GUILD_MEMBER_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GUILD_MEMBER_LIST_1>, cb?: CallbackFunction<S_GUILD_MEMBER_LIST_1>);
  hook(packet: 'S_GUILD_STORE_SELL_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_GUILD_STORE_SELL_LIST_1>, cb?: CallbackFunction<S_GUILD_STORE_SELL_LIST_1>);
  hook(packet: 'S_HIT_COMBO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_HIT_COMBO_1>, cb?: CallbackFunction<S_HIT_COMBO_1>);
  hook(packet: 'S_IMAGE_DATA', version: 1 | '*', options?: HookOptions | CallbackFunction<S_IMAGE_DATA_1>, cb?: CallbackFunction<S_IMAGE_DATA_1>);
  hook(packet: 'S_INVEN_CHANGEDSLOT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_INVEN_CHANGEDSLOT_1>, cb?: CallbackFunction<S_INVEN_CHANGEDSLOT_1>);
  hook(packet: 'S_ITEM_COLORING_BAG', version: 1 | '*', options?: HookOptions | CallbackFunction<S_ITEM_COLORING_BAG_1>, cb?: CallbackFunction<S_ITEM_COLORING_BAG_1>);
  hook(packet: 'S_LEARN_EP_PERK', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LEARN_EP_PERK_1>, cb?: CallbackFunction<S_LEARN_EP_PERK_1>);
  hook(packet: 'S_LEAVE_GUILD', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LEAVE_GUILD_1>, cb?: CallbackFunction<S_LEAVE_GUILD_1>);
  hook(packet: 'S_LEAVE_PARTY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LEAVE_PARTY_1>, cb?: CallbackFunction<S_LEAVE_PARTY_1>);
  hook(packet: 'S_LOAD_ACHIEVEMENT_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LOAD_ACHIEVEMENT_LIST_2>, cb?: CallbackFunction<S_LOAD_ACHIEVEMENT_LIST_2>);
  hook(packet: 'S_LOAD_CLIENT_ACCOUNT_SETTING', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOAD_CLIENT_ACCOUNT_SETTING_1>, cb?: CallbackFunction<S_LOAD_CLIENT_ACCOUNT_SETTING_1>);
  hook(packet: 'S_LOAD_CLIENT_USER_SETTING', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOAD_CLIENT_USER_SETTING_1>, cb?: CallbackFunction<S_LOAD_CLIENT_USER_SETTING_1>);
  hook(packet: 'S_LOAD_EP_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOAD_EP_INFO_1>, cb?: CallbackFunction<S_LOAD_EP_INFO_1>);
  hook(packet: 'S_LOAD_TELEPORT_TO_POS_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOAD_TELEPORT_TO_POS_LIST_1>, cb?: CallbackFunction<S_LOAD_TELEPORT_TO_POS_LIST_1>);
  hook(packet: 'S_LOCKON_YOU', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOCKON_YOU_1>, cb?: CallbackFunction<S_LOCKON_YOU_1>);
  hook(packet: 'S_LOGOUT_PARTY_MEMBER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_LOGOUT_PARTY_MEMBER_1>, cb?: CallbackFunction<S_LOGOUT_PARTY_MEMBER_1>);
  hook(packet: 'S_MOUNT_VEHICLE_EX', version: 1 | '*', options?: HookOptions | CallbackFunction<S_MOUNT_VEHICLE_EX_1>, cb?: CallbackFunction<S_MOUNT_VEHICLE_EX_1>);
  hook(packet: 'S_MOVE_SHUTTLE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_MOVE_SHUTTLE_1>, cb?: CallbackFunction<S_MOVE_SHUTTLE_1>);
  hook(packet: 'S_NOCTAN_VARIATION_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NOCTAN_VARIATION_INFO_1>, cb?: CallbackFunction<S_NOCTAN_VARIATION_INFO_1>);
  hook(packet: 'S_NOTIFY_GUILD_QUEST_URGENT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NOTIFY_GUILD_QUEST_URGENT_1>, cb?: CallbackFunction<S_NOTIFY_GUILD_QUEST_URGENT_1>);
  hook(packet: 'S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA_1>, cb?: CallbackFunction<S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA_1>);
  hook(packet: 'S_NPC_MENU_SELECT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NPC_MENU_SELECT_1>, cb?: CallbackFunction<S_NPC_MENU_SELECT_1>);
  hook(packet: 'S_NPC_OCCUPIER_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NPC_OCCUPIER_INFO_1>, cb?: CallbackFunction<S_NPC_OCCUPIER_INFO_1>);
  hook(packet: 'S_NPC_TARGET_USER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_NPC_TARGET_USER_1>, cb?: CallbackFunction<S_NPC_TARGET_USER_1>);
  hook(packet: 'S_OPEN_AWESOMIUM_WEB_URL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_OPEN_AWESOMIUM_WEB_URL_1>, cb?: CallbackFunction<S_OPEN_AWESOMIUM_WEB_URL_1>);
  hook(packet: 'S_OTHER_USER_APPLY_PARTY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_OTHER_USER_APPLY_PARTY_1>, cb?: CallbackFunction<S_OTHER_USER_APPLY_PARTY_1>);
  hook(packet: 'S_PARTY_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PARTY_INFO_1>, cb?: CallbackFunction<S_PARTY_INFO_1>);
  hook(packet: 'S_PARTY_MARKER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MARKER_1>, cb?: CallbackFunction<S_PARTY_MARKER_1>);
  hook(packet: 'S_PARTY_MEMBER_ABNORMAL_CLEAR', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_ABNORMAL_CLEAR_1>, cb?: CallbackFunction<S_PARTY_MEMBER_ABNORMAL_CLEAR_1>);
  hook(packet: 'S_PARTY_MEMBER_INFO', version: 3 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_INFO_3>, cb?: CallbackFunction<S_PARTY_MEMBER_INFO_3>);
  hook(packet: 'S_PLAYER_CHANGE_EP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_EP_1>, cb?: CallbackFunction<S_PLAYER_CHANGE_EP_1>);
  hook(packet: 'S_PLAYER_CHANGE_FLIGHT_ENERGY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_FLIGHT_ENERGY_1>, cb?: CallbackFunction<S_PLAYER_CHANGE_FLIGHT_ENERGY_1>);
  hook(packet: 'S_PLAYER_CHANGE_MP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_MP_1>, cb?: CallbackFunction<S_PLAYER_CHANGE_MP_1>);
  hook(packet: 'S_PLAYER_CHANGE_STAMINA', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_STAMINA_1>, cb?: CallbackFunction<S_PLAYER_CHANGE_STAMINA_1>);
  hook(packet: 'S_PLAYER_RESET_EP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_RESET_EP_1>, cb?: CallbackFunction<S_PLAYER_RESET_EP_1>);
  hook(packet: 'S_PLAY_ANIMATION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAY_ANIMATION_1>, cb?: CallbackFunction<S_PLAY_ANIMATION_1>);
  hook(packet: 'S_PLAY_EFFECT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAY_EFFECT_1>, cb?: CallbackFunction<S_PLAY_EFFECT_1>);
  hook(packet: 'S_PLAY_MOVIE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAY_MOVIE_1>, cb?: CallbackFunction<S_PLAY_MOVIE_1>);
  hook(packet: 'S_PLAY_SOUND', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PLAY_SOUND_1>, cb?: CallbackFunction<S_PLAY_SOUND_1>);
  hook(packet: 'S_POINT_STORE_SELL_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_POINT_STORE_SELL_LIST_1>, cb?: CallbackFunction<S_POINT_STORE_SELL_LIST_1>);
  hook(packet: 'S_PREMIUM_SLOT_OFF', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PREMIUM_SLOT_OFF_1>, cb?: CallbackFunction<S_PREMIUM_SLOT_OFF_1>);
  hook(packet: 'S_PREPARE_EXIT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PREPARE_EXIT_1>, cb?: CallbackFunction<S_PREPARE_EXIT_1>);
  hook(packet: 'S_PREPARE_RETURN_TO_LOBBY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PREPARE_RETURN_TO_LOBBY_1>, cb?: CallbackFunction<S_PREPARE_RETURN_TO_LOBBY_1>);
  hook(packet: 'S_PREVIEW_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PREVIEW_ITEM_1>, cb?: CallbackFunction<S_PREVIEW_ITEM_1>);
  hook(packet: 'S_PRIVATE_CHAT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PRIVATE_CHAT_1>, cb?: CallbackFunction<S_PRIVATE_CHAT_1>);
  hook(packet: 'S_PRODUCE_CRITICAL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_PRODUCE_CRITICAL_1>, cb?: CallbackFunction<S_PRODUCE_CRITICAL_1>);
  hook(packet: 'S_QUEST_BALLOON', version: 1 | '*', options?: HookOptions | CallbackFunction<S_QUEST_BALLOON_1>, cb?: CallbackFunction<S_QUEST_BALLOON_1>);
  hook(packet: 'S_REJECT_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REJECT_CONTRACT_1>, cb?: CallbackFunction<S_REJECT_CONTRACT_1>);
  hook(packet: 'S_REMOVE_BLOCKED_USER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REMOVE_BLOCKED_USER_1>, cb?: CallbackFunction<S_REMOVE_BLOCKED_USER_1>);
  hook(packet: 'S_REMOVE_EFFECT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REMOVE_EFFECT_1>, cb?: CallbackFunction<S_REMOVE_EFFECT_1>);
  hook(packet: 'S_REPLY_NONDB_ITEM_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REPLY_NONDB_ITEM_INFO_1>, cb?: CallbackFunction<S_REPLY_NONDB_ITEM_INFO_1>);
  hook(packet: 'S_REPLY_REQUEST_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REPLY_REQUEST_CONTRACT_1>, cb?: CallbackFunction<S_REPLY_REQUEST_CONTRACT_1>);
  hook(packet: 'S_REQUEST_CITY_WAR_MAP_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_1>, cb?: CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_1>);
  hook(packet: 'S_REQUEST_CITY_WAR_MAP_INFO_DETAIL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_DETAIL_1>, cb?: CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_DETAIL_1>);
  hook(packet: 'S_REQUEST_CITY_WAR_MAP_INFO_END', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_END_1>, cb?: CallbackFunction<S_REQUEST_CITY_WAR_MAP_INFO_END_1>);
  hook(packet: 'S_REQUEST_CONTRACT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_CONTRACT_1>, cb?: CallbackFunction<S_REQUEST_CONTRACT_1>);
  hook(packet: 'S_REQUEST_DESPAWN_SERVANT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_DESPAWN_SERVANT_1>, cb?: CallbackFunction<S_REQUEST_DESPAWN_SERVANT_1>);
  hook(packet: 'S_REQUEST_REACTION_POS_TICK', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_REACTION_POS_TICK_1>, cb?: CallbackFunction<S_REQUEST_REACTION_POS_TICK_1>);
  hook(packet: 'S_REQUEST_SECOND_PASSWORD_AUTH', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_SECOND_PASSWORD_AUTH_1>, cb?: CallbackFunction<S_REQUEST_SECOND_PASSWORD_AUTH_1>);
  hook(packet: 'S_REQUEST_STYLE_SHOP_MARK_PRODUCTLIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_STYLE_SHOP_MARK_PRODUCTLIST_1>, cb?: CallbackFunction<S_REQUEST_STYLE_SHOP_MARK_PRODUCTLIST_1>);
  hook(packet: 'S_RESET_EP_PERK', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RESET_EP_PERK_1>, cb?: CallbackFunction<S_RESET_EP_PERK_1>);
  hook(packet: 'S_RESPONSE_GAMESTAT_PONG', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RESPONSE_GAMESTAT_PONG_1>, cb?: CallbackFunction<S_RESPONSE_GAMESTAT_PONG_1>);
  hook(packet: 'S_RESULT_BIDDING_DICE_THROW', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RESULT_BIDDING_DICE_THROW_1>, cb?: CallbackFunction<S_RESULT_BIDDING_DICE_THROW_1>);
  hook(packet: 'S_RESULT_ITEM_BIDDING', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RESULT_ITEM_BIDDING_1>, cb?: CallbackFunction<S_RESULT_ITEM_BIDDING_1>);
  hook(packet: 'S_RETURN_TO_LOBBY', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RETURN_TO_LOBBY_1>, cb?: CallbackFunction<S_RETURN_TO_LOBBY_1>);
  hook(packet: 'S_RP_SKILL_POLISHING_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_RP_SKILL_POLISHING_LIST_1>, cb?: CallbackFunction<S_RP_SKILL_POLISHING_LIST_1>);
  hook(packet: 'S_SHOW_AWESOMIUMWEB_SHOP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SHOW_AWESOMIUMWEB_SHOP_1>, cb?: CallbackFunction<S_SHOW_AWESOMIUMWEB_SHOP_1>);
  hook(packet: 'S_SHOW_PARTY_MATCH_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SHOW_PARTY_MATCH_INFO_1>, cb?: CallbackFunction<S_SHOW_PARTY_MATCH_INFO_1>);
  hook(packet: 'S_SHOW_PEGASUS_MAP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SHOW_PEGASUS_MAP_1>, cb?: CallbackFunction<S_SHOW_PEGASUS_MAP_1>);
  hook(packet: 'S_SHOW_USER_EP_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SHOW_USER_EP_INFO_1>, cb?: CallbackFunction<S_SHOW_USER_EP_INFO_1>);
  hook(packet: 'S_SKILL_ATTENTION_TARGET', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SKILL_ATTENTION_TARGET_1>, cb?: CallbackFunction<S_SKILL_ATTENTION_TARGET_1>);
  hook(packet: 'S_SOCIAL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SOCIAL_1>, cb?: CallbackFunction<S_SOCIAL_1>);
  hook(packet: 'S_START_CLIMBING', version: 1 | '*', options?: HookOptions | CallbackFunction<S_START_CLIMBING_1>, cb?: CallbackFunction<S_START_CLIMBING_1>);
  hook(packet: 'S_START_COOLTIME_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<S_START_COOLTIME_ITEM_1>, cb?: CallbackFunction<S_START_COOLTIME_ITEM_1>);
  hook(packet: 'S_STICK_TO_USER_START', version: 1 | '*', options?: HookOptions | CallbackFunction<S_STICK_TO_USER_START_1>, cb?: CallbackFunction<S_STICK_TO_USER_START_1>);
  hook(packet: 'S_STORE_SELL_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_STORE_SELL_LIST_1>, cb?: CallbackFunction<S_STORE_SELL_LIST_1>);
  hook(packet: 'S_SUCCESS_COUNTER', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SUCCESS_COUNTER_1>, cb?: CallbackFunction<S_SUCCESS_COUNTER_1>);
  hook(packet: 'S_SYSTEM_MESSAGE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SYSTEM_MESSAGE_1>, cb?: CallbackFunction<S_SYSTEM_MESSAGE_1>);
  hook(packet: 'S_SYSTEM_MESSAGE_LOOT_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SYSTEM_MESSAGE_LOOT_ITEM_1>, cb?: CallbackFunction<S_SYSTEM_MESSAGE_LOOT_ITEM_1>);
  hook(packet: 'S_SYSTEM_MESSAGE_LOOT_SPECIAL_ITEM', version: 1 | '*', options?: HookOptions | CallbackFunction<S_SYSTEM_MESSAGE_LOOT_SPECIAL_ITEM_1>, cb?: CallbackFunction<S_SYSTEM_MESSAGE_LOOT_SPECIAL_ITEM_1>);
  hook(packet: 'S_TELEPORT_TO_CAMP', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TELEPORT_TO_CAMP_1>, cb?: CallbackFunction<S_TELEPORT_TO_CAMP_1>);
  hook(packet: 'S_TRADE_BROKER_DEAL_INFO_UPDATE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_DEAL_INFO_UPDATE_1>, cb?: CallbackFunction<S_TRADE_BROKER_DEAL_INFO_UPDATE_1>);
  hook(packet: 'S_TRADE_BROKER_DEAL_SUGGESTED', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_DEAL_SUGGESTED_1>, cb?: CallbackFunction<S_TRADE_BROKER_DEAL_SUGGESTED_1>);
  hook(packet: 'S_TRADE_BROKER_REQUEST_DEAL_RESULT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_REQUEST_DEAL_RESULT_1>, cb?: CallbackFunction<S_TRADE_BROKER_REQUEST_DEAL_RESULT_1>);
  hook(packet: 'S_TRADE_BROKER_SUGGEST_DEAL', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_SUGGEST_DEAL_1>, cb?: CallbackFunction<S_TRADE_BROKER_SUGGEST_DEAL_1>);
  hook(packet: 'S_TRADE_BROKER_WAITING_ITEM_LIST', version: 1 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_WAITING_ITEM_LIST_1>, cb?: CallbackFunction<S_TRADE_BROKER_WAITING_ITEM_LIST_1>);
  hook(packet: 'S_UNMOUNT_VEHICLE_EX', version: 1 | '*', options?: HookOptions | CallbackFunction<S_UNMOUNT_VEHICLE_EX_1>, cb?: CallbackFunction<S_UNMOUNT_VEHICLE_EX_1>);
  hook(packet: 'S_UPDATE_ACHIEVEMENT_PROGRESS', version: 1 | '*', options?: HookOptions | CallbackFunction<S_UPDATE_ACHIEVEMENT_PROGRESS_1>, cb?: CallbackFunction<S_UPDATE_ACHIEVEMENT_PROGRESS_1>);
  hook(packet: 'S_UPDATE_FRIEND_INFO', version: 1 | '*', options?: HookOptions | CallbackFunction<S_UPDATE_FRIEND_INFO_1>, cb?: CallbackFunction<S_UPDATE_FRIEND_INFO_1>);
  hook(packet: 'S_UPDATE_GUILD_QUEST_STATUS', version: 1 | '*', options?: HookOptions | CallbackFunction<S_UPDATE_GUILD_QUEST_STATUS_1>, cb?: CallbackFunction<S_UPDATE_GUILD_QUEST_STATUS_1>);
  hook(packet: 'S_USER_APPEARANCE_CHANGE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_USER_APPEARANCE_CHANGE_1>, cb?: CallbackFunction<S_USER_APPEARANCE_CHANGE_1>);
  hook(packet: 'S_USER_CHANGE_NAME', version: 1 | '*', options?: HookOptions | CallbackFunction<S_USER_CHANGE_NAME_1>, cb?: CallbackFunction<S_USER_CHANGE_NAME_1>);
  hook(packet: 'S_USER_EFFECT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_USER_EFFECT_1>, cb?: CallbackFunction<S_USER_EFFECT_1>);
  hook(packet: 'S_USER_MOVETYPE', version: 1 | '*', options?: HookOptions | CallbackFunction<S_USER_MOVETYPE_1>, cb?: CallbackFunction<S_USER_MOVETYPE_1>);
  hook(packet: 'S_USER_SITUATION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_USER_SITUATION_1>, cb?: CallbackFunction<S_USER_SITUATION_1>);
  hook(packet: 'S_VILLAGE_LIST_TO_TELEPORT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_VILLAGE_LIST_TO_TELEPORT_1>, cb?: CallbackFunction<S_VILLAGE_LIST_TO_TELEPORT_1>);
  hook(packet: 'S_VISIT_NEW_SECTION', version: 1 | '*', options?: HookOptions | CallbackFunction<S_VISIT_NEW_SECTION_1>, cb?: CallbackFunction<S_VISIT_NEW_SECTION_1>);
  hook(packet: 'S_VOTE_RESET_ALL_DUNGEON', version: 1 | '*', options?: HookOptions | CallbackFunction<S_VOTE_RESET_ALL_DUNGEON_1>, cb?: CallbackFunction<S_VOTE_RESET_ALL_DUNGEON_1>);
  hook(packet: 'S_WEAK_POINT', version: 1 | '*', options?: HookOptions | CallbackFunction<S_WEAK_POINT_1>, cb?: CallbackFunction<S_WEAK_POINT_1>);
  hook(packet: 'C_CHANGE_PARTY_MANAGER', version: 2 | '*', options?: HookOptions | CallbackFunction<C_CHANGE_PARTY_MANAGER_2>, cb?: CallbackFunction<C_CHANGE_PARTY_MANAGER_2>);
  hook(packet: 'C_COMMIT_CHANGE_USER_APPEARANCE', version: 2 | '*', options?: HookOptions | CallbackFunction<C_COMMIT_CHANGE_USER_APPEARANCE_2>, cb?: CallbackFunction<C_COMMIT_CHANGE_USER_APPEARANCE_2>);
  hook(packet: 'C_CREST_APPLY', version: 2 | '*', options?: HookOptions | CallbackFunction<C_CREST_APPLY_2>, cb?: CallbackFunction<C_CREST_APPLY_2>);
  hook(packet: 'C_CREST_APPLY_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<C_CREST_APPLY_LIST_2>, cb?: CallbackFunction<C_CREST_APPLY_LIST_2>);
  hook(packet: 'C_END_CLIMBING', version: 2 | '*', options?: HookOptions | CallbackFunction<C_END_CLIMBING_2>, cb?: CallbackFunction<C_END_CLIMBING_2>);
  hook(packet: 'C_LOGIN_ARBITER', version: 2 | '*', options?: HookOptions | CallbackFunction<C_LOGIN_ARBITER_2>, cb?: CallbackFunction<C_LOGIN_ARBITER_2>);
  hook(packet: 'C_MERGE_ITEM', version: 2 | '*', options?: HookOptions | CallbackFunction<C_MERGE_ITEM_2>, cb?: CallbackFunction<C_MERGE_ITEM_2>);
  hook(packet: 'C_NPC_CONTACT', version: 2 | '*', options?: HookOptions | CallbackFunction<C_NPC_CONTACT_2>, cb?: CallbackFunction<C_NPC_CONTACT_2>);
  hook(packet: 'C_REQUEST_PARTY_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_PARTY_INFO_2>, cb?: CallbackFunction<C_REQUEST_PARTY_INFO_2>);
  hook(packet: 'C_REQUEST_PRIVATE_CHANNEL_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_PRIVATE_CHANNEL_INFO_2>, cb?: CallbackFunction<C_REQUEST_PRIVATE_CHANNEL_INFO_2>);
  hook(packet: 'C_REQUEST_USER_PAPERDOLL_INFO', version: 3 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_USER_PAPERDOLL_INFO_3>, cb?: CallbackFunction<C_REQUEST_USER_PAPERDOLL_INFO_3>);
  hook(packet: 'C_REQUEST_USER_PAPERDOLL_INFO_WITH_GAMEID', version: 3 | '*', options?: HookOptions | CallbackFunction<C_REQUEST_USER_PAPERDOLL_INFO_WITH_GAMEID_3>, cb?: CallbackFunction<C_REQUEST_USER_PAPERDOLL_INFO_WITH_GAMEID_3>);
  hook(packet: 'C_REVIVE_NOW', version: 2 | '*', options?: HookOptions | CallbackFunction<C_REVIVE_NOW_2>, cb?: CallbackFunction<C_REVIVE_NOW_2>);
  hook(packet: 'C_TRADE_BROKER_BUY_IT_NOW', version: 2 | '*', options?: HookOptions | CallbackFunction<C_TRADE_BROKER_BUY_IT_NOW_2>, cb?: CallbackFunction<C_TRADE_BROKER_BUY_IT_NOW_2>);
  hook(packet: 'C_VIEW_WARE', version: 2 | '*', options?: HookOptions | CallbackFunction<C_VIEW_WARE_2>, cb?: CallbackFunction<C_VIEW_WARE_2>);
  hook(packet: 'S_ABNORMALITY_FAIL', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_FAIL_2>, cb?: CallbackFunction<S_ABNORMALITY_FAIL_2>);
  hook(packet: 'S_ABNORMALITY_SCALE_UP', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_SCALE_UP_2>, cb?: CallbackFunction<S_ABNORMALITY_SCALE_UP_2>);
  hook(packet: 'S_ADD_BLOCKED_USER', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ADD_BLOCKED_USER_2>, cb?: CallbackFunction<S_ADD_BLOCKED_USER_2>);
  hook(packet: 'S_ADMIN_HOLD_CHARACTER', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ADMIN_HOLD_CHARACTER_2>, cb?: CallbackFunction<S_ADMIN_HOLD_CHARACTER_2>);
  hook(packet: 'S_ANSWER_INTERACTIVE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ANSWER_INTERACTIVE_2>, cb?: CallbackFunction<S_ANSWER_INTERACTIVE_2>);
  hook(packet: 'S_AVAILABLE_SOCIAL_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_AVAILABLE_SOCIAL_LIST_2>, cb?: CallbackFunction<S_AVAILABLE_SOCIAL_LIST_2>);
  hook(packet: 'S_CHANGE_EVENT_MATCHING_STATE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_EVENT_MATCHING_STATE_2>, cb?: CallbackFunction<S_CHANGE_EVENT_MATCHING_STATE_2>);
  hook(packet: 'S_CHANGE_PARTY_MANAGER', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CHANGE_PARTY_MANAGER_2>, cb?: CallbackFunction<S_CHANGE_PARTY_MANAGER_2>);
  hook(packet: 'S_COLLECTION_PICKEND', version: 2 | '*', options?: HookOptions | CallbackFunction<S_COLLECTION_PICKEND_2>, cb?: CallbackFunction<S_COLLECTION_PICKEND_2>);
  hook(packet: 'S_COLLECTION_PICKSTART', version: 2 | '*', options?: HookOptions | CallbackFunction<S_COLLECTION_PICKSTART_2>, cb?: CallbackFunction<S_COLLECTION_PICKSTART_2>);
  hook(packet: 'S_CREATURE_ROTATE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CREATURE_ROTATE_2>, cb?: CallbackFunction<S_CREATURE_ROTATE_2>);
  hook(packet: 'S_CREST_APPLY', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CREST_APPLY_2>, cb?: CallbackFunction<S_CREST_APPLY_2>);
  hook(packet: 'S_CREST_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CREST_INFO_2>, cb?: CallbackFunction<S_CREST_INFO_2>);
  hook(packet: 'S_CREST_MESSAGE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CREST_MESSAGE_2>, cb?: CallbackFunction<S_CREST_MESSAGE_2>);
  hook(packet: 'S_CURRENT_CHANNEL', version: 2 | '*', options?: HookOptions | CallbackFunction<S_CURRENT_CHANNEL_2>, cb?: CallbackFunction<S_CURRENT_CHANNEL_2>);
  hook(packet: 'S_DEAD_LOCATION', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DEAD_LOCATION_2>, cb?: CallbackFunction<S_DEAD_LOCATION_2>);
  hook(packet: 'S_DESPAWN_BONFIRE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_BONFIRE_2>, cb?: CallbackFunction<S_DESPAWN_BONFIRE_2>);
  hook(packet: 'S_DESPAWN_BUILD_OBJECT', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_BUILD_OBJECT_2>, cb?: CallbackFunction<S_DESPAWN_BUILD_OBJECT_2>);
  hook(packet: 'S_DESPAWN_COLLECTION', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_COLLECTION_2>, cb?: CallbackFunction<S_DESPAWN_COLLECTION_2>);
  hook(packet: 'S_DESPAWN_SHUTTLE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_SHUTTLE_2>, cb?: CallbackFunction<S_DESPAWN_SHUTTLE_2>);
  hook(packet: 'S_DUNGEON_COOL_TIME_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DUNGEON_COOL_TIME_LIST_2>, cb?: CallbackFunction<S_DUNGEON_COOL_TIME_LIST_2>);
  hook(packet: 'S_DUNGEON_EVENT_MESSAGE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_DUNGEON_EVENT_MESSAGE_2>, cb?: CallbackFunction<S_DUNGEON_EVENT_MESSAGE_2>);
  hook(packet: 'S_ENABLE_DISABLE_SELLABLE_ITEM_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ENABLE_DISABLE_SELLABLE_ITEM_LIST_2>, cb?: CallbackFunction<S_ENABLE_DISABLE_SELLABLE_ITEM_LIST_2>);
  hook(packet: 'S_FEARMOVE_END', version: 2 | '*', options?: HookOptions | CallbackFunction<S_FEARMOVE_END_2>, cb?: CallbackFunction<S_FEARMOVE_END_2>);
  hook(packet: 'S_FEARMOVE_STAGE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_FEARMOVE_STAGE_2>, cb?: CallbackFunction<S_FEARMOVE_STAGE_2>);
  hook(packet: 'S_FIELD_POINT_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_FIELD_POINT_INFO_2>, cb?: CallbackFunction<S_FIELD_POINT_INFO_2>);
  hook(packet: 'S_GACHA_END', version: 2 | '*', options?: HookOptions | CallbackFunction<S_GACHA_END_2>, cb?: CallbackFunction<S_GACHA_END_2>);
  hook(packet: 'S_GACHA_START', version: 2 | '*', options?: HookOptions | CallbackFunction<S_GACHA_START_2>, cb?: CallbackFunction<S_GACHA_START_2>);
  hook(packet: 'S_GMEVENT_RECV_REWARD', version: 2 | '*', options?: HookOptions | CallbackFunction<S_GMEVENT_RECV_REWARD_2>, cb?: CallbackFunction<S_GMEVENT_RECV_REWARD_2>);
  hook(packet: 'S_GUILD_NAME', version: 2 | '*', options?: HookOptions | CallbackFunction<S_GUILD_NAME_2>, cb?: CallbackFunction<S_GUILD_NAME_2>);
  hook(packet: 'S_HOLD_ABNORMALITY_ADD', version: 2 | '*', options?: HookOptions | CallbackFunction<S_HOLD_ABNORMALITY_ADD_2>, cb?: CallbackFunction<S_HOLD_ABNORMALITY_ADD_2>);
  hook(packet: 'S_INVEN_USERDATA', version: 2 | '*', options?: HookOptions | CallbackFunction<S_INVEN_USERDATA_2>, cb?: CallbackFunction<S_INVEN_USERDATA_2>);
  hook(packet: 'S_ITEM_CUSTOM_STRING', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ITEM_CUSTOM_STRING_2>, cb?: CallbackFunction<S_ITEM_CUSTOM_STRING_2>);
  hook(packet: 'S_ITEM_EXPLOSION_RESULT', version: 2 | '*', options?: HookOptions | CallbackFunction<S_ITEM_EXPLOSION_RESULT_2>, cb?: CallbackFunction<S_ITEM_EXPLOSION_RESULT_2>);
  hook(packet: 'S_JOIN_PRIVATE_CHANNEL', version: 2 | '*', options?: HookOptions | CallbackFunction<S_JOIN_PRIVATE_CHANNEL_2>, cb?: CallbackFunction<S_JOIN_PRIVATE_CHANNEL_2>);
  hook(packet: 'S_LEAVE_PARTY_MEMBER', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LEAVE_PARTY_MEMBER_2>, cb?: CallbackFunction<S_LEAVE_PARTY_MEMBER_2>);
  hook(packet: 'S_LEAVE_PRIVATE_CHANNEL', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LEAVE_PRIVATE_CHANNEL_2>, cb?: CallbackFunction<S_LEAVE_PRIVATE_CHANNEL_2>);
  hook(packet: 'S_LOADING_SCREEN_CONTROL_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LOADING_SCREEN_CONTROL_INFO_2>, cb?: CallbackFunction<S_LOADING_SCREEN_CONTROL_INFO_2>);
  hook(packet: 'S_LOAD_DUNGEON_SOUND_HINT', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LOAD_DUNGEON_SOUND_HINT_2>, cb?: CallbackFunction<S_LOAD_DUNGEON_SOUND_HINT_2>);
  hook(packet: 'S_LOGIN_ACCOUNT_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_LOGIN_ACCOUNT_INFO_2>, cb?: CallbackFunction<S_LOGIN_ACCOUNT_INFO_2>);
  hook(packet: 'S_MOUNT_VEHICLE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_MOUNT_VEHICLE_2>, cb?: CallbackFunction<S_MOUNT_VEHICLE_2>);
  hook(packet: 'S_MUTE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_MUTE_2>, cb?: CallbackFunction<S_MUTE_2>);
  hook(packet: 'S_NPCGUILD_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_NPCGUILD_LIST_2>, cb?: CallbackFunction<S_NPCGUILD_LIST_2>);
  hook(packet: 'S_NPC_STATUS', version: 2 | '*', options?: HookOptions | CallbackFunction<S_NPC_STATUS_2>, cb?: CallbackFunction<S_NPC_STATUS_2>);
  hook(packet: 'S_PARTY_MATCH_LINK', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MATCH_LINK_2>, cb?: CallbackFunction<S_PARTY_MATCH_LINK_2>);
  hook(packet: 'S_PARTY_MEMBER_ABNORMAL_DEL', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_ABNORMAL_DEL_2>, cb?: CallbackFunction<S_PARTY_MEMBER_ABNORMAL_DEL_2>);
  hook(packet: 'S_PARTY_MEMBER_BUFF_UPDATE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_BUFF_UPDATE_2>, cb?: CallbackFunction<S_PARTY_MEMBER_BUFF_UPDATE_2>);
  hook(packet: 'S_PARTY_MEMBER_CHANGE_MP', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_CHANGE_MP_2>, cb?: CallbackFunction<S_PARTY_MEMBER_CHANGE_MP_2>);
  hook(packet: 'S_PARTY_MEMBER_CHANGE_STAMINA', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_CHANGE_STAMINA_2>, cb?: CallbackFunction<S_PARTY_MEMBER_CHANGE_STAMINA_2>);
  hook(packet: 'S_PLAYER_CHANGE_ALL_PROF', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_ALL_PROF_2>, cb?: CallbackFunction<S_PLAYER_CHANGE_ALL_PROF_2>);
  hook(packet: 'S_PLAYER_CHANGE_EXP', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_EXP_2>, cb?: CallbackFunction<S_PLAYER_CHANGE_EXP_2>);
  hook(packet: 'S_PLAYER_CHANGE_PROF', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_CHANGE_PROF_2>, cb?: CallbackFunction<S_PLAYER_CHANGE_PROF_2>);
  hook(packet: 'S_PREMIUM_SLOT_DATALIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PREMIUM_SLOT_DATALIST_2>, cb?: CallbackFunction<S_PREMIUM_SLOT_DATALIST_2>);
  hook(packet: 'S_PRIVATE_CHANNEL_NOTICE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_PRIVATE_CHANNEL_NOTICE_2>, cb?: CallbackFunction<S_PRIVATE_CHANNEL_NOTICE_2>);
  hook(packet: 'S_QUEST_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_QUEST_INFO_2>, cb?: CallbackFunction<S_QUEST_INFO_2>);
  hook(packet: 'S_REQUEST_PRIVATE_CHANNEL_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_PRIVATE_CHANNEL_INFO_2>, cb?: CallbackFunction<S_REQUEST_PRIVATE_CHANNEL_INFO_2>);
  hook(packet: 'S_RESULT_EVENT_SEED', version: 2 | '*', options?: HookOptions | CallbackFunction<S_RESULT_EVENT_SEED_2>, cb?: CallbackFunction<S_RESULT_EVENT_SEED_2>);
  hook(packet: 'S_SHORTCUT_CHANGE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_SHORTCUT_CHANGE_2>, cb?: CallbackFunction<S_SHORTCUT_CHANGE_2>);
  hook(packet: 'S_SKILL_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_SKILL_LIST_2>, cb?: CallbackFunction<S_SKILL_LIST_2>);
  hook(packet: 'S_SPAWN_BONFIRE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_BONFIRE_2>, cb?: CallbackFunction<S_SPAWN_BONFIRE_2>);
  hook(packet: 'S_SPAWN_BUILD_OBJECT', version: 2 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_BUILD_OBJECT_2>, cb?: CallbackFunction<S_SPAWN_BUILD_OBJECT_2>);
  hook(packet: 'S_SPAWN_EVENT_SEED', version: 2 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_EVENT_SEED_2>, cb?: CallbackFunction<S_SPAWN_EVENT_SEED_2>);
  hook(packet: 'S_STICK_TO_USER_END', version: 2 | '*', options?: HookOptions | CallbackFunction<S_STICK_TO_USER_END_2>, cb?: CallbackFunction<S_STICK_TO_USER_END_2>);
  hook(packet: 'S_TARGET_INFO', version: 2 | '*', options?: HookOptions | CallbackFunction<S_TARGET_INFO_2>, cb?: CallbackFunction<S_TARGET_INFO_2>);
  hook(packet: 'S_TRADE_BROKER_HISTORY_ITEM_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_TRADE_BROKER_HISTORY_ITEM_LIST_2>, cb?: CallbackFunction<S_TRADE_BROKER_HISTORY_ITEM_LIST_2>);
  hook(packet: 'S_UNMOUNT_VEHICLE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_UNMOUNT_VEHICLE_2>, cb?: CallbackFunction<S_UNMOUNT_VEHICLE_2>);
  hook(packet: 'S_USER_BLOCK_LIST', version: 2 | '*', options?: HookOptions | CallbackFunction<S_USER_BLOCK_LIST_2>, cb?: CallbackFunction<S_USER_BLOCK_LIST_2>);
  hook(packet: 'S_USER_CHANGE_FACE_CUSTOM', version: 2 | '*', options?: HookOptions | CallbackFunction<S_USER_CHANGE_FACE_CUSTOM_2>, cb?: CallbackFunction<S_USER_CHANGE_FACE_CUSTOM_2>);
  hook(packet: 'S_USER_LEVELUP', version: 2 | '*', options?: HookOptions | CallbackFunction<S_USER_LEVELUP_2>, cb?: CallbackFunction<S_USER_LEVELUP_2>);
  hook(packet: 'S_USER_LOCATION_IN_ACTION', version: 2 | '*', options?: HookOptions | CallbackFunction<S_USER_LOCATION_IN_ACTION_2>, cb?: CallbackFunction<S_USER_LOCATION_IN_ACTION_2>);
  hook(packet: 'S_USER_WEAPON_APPEARANCE_CHANGE', version: 2 | '*', options?: HookOptions | CallbackFunction<S_USER_WEAPON_APPEARANCE_CHANGE_2>, cb?: CallbackFunction<S_USER_WEAPON_APPEARANCE_CHANGE_2>);
  hook(packet: 'S_VIEW_WARE_EX', version: 2 | '*', options?: HookOptions | CallbackFunction<S_VIEW_WARE_EX_2>, cb?: CallbackFunction<S_VIEW_WARE_EX_2>);
  hook(packet: 'C_CANCEL_SKILL', version: 3 | '*', options?: HookOptions | CallbackFunction<C_CANCEL_SKILL_3>, cb?: CallbackFunction<C_CANCEL_SKILL_3>);
  hook(packet: 'C_CAN_LOCKON_TARGET', version: 3 | '*', options?: HookOptions | CallbackFunction<C_CAN_LOCKON_TARGET_3>, cb?: CallbackFunction<C_CAN_LOCKON_TARGET_3>);
  hook(packet: 'C_DEL_ITEM', version: 3 | '*', options?: HookOptions | CallbackFunction<C_DEL_ITEM_3>, cb?: CallbackFunction<C_DEL_ITEM_3>);
  hook(packet: 'C_NOTIMELINE_SKILL', version: 3 | '*', options?: HookOptions | CallbackFunction<C_NOTIMELINE_SKILL_3>, cb?: CallbackFunction<C_NOTIMELINE_SKILL_3>);
  hook(packet: 'C_PUT_WARE_ITEM', version: 3 | '*', options?: HookOptions | CallbackFunction<C_PUT_WARE_ITEM_3>, cb?: CallbackFunction<C_PUT_WARE_ITEM_3>);
  hook(packet: 'C_SHOW_ITEM_TOOLTIP_EX', version: 3 | '*', options?: HookOptions | CallbackFunction<C_SHOW_ITEM_TOOLTIP_EX_3>, cb?: CallbackFunction<C_SHOW_ITEM_TOOLTIP_EX_3>);
  hook(packet: 'C_USE_ITEM', version: 3 | '*', options?: HookOptions | CallbackFunction<C_USE_ITEM_3>, cb?: CallbackFunction<C_USE_ITEM_3>);
  hook(packet: 'S_ABNORMALITY_BEGIN', version: 4 | '*', options?: HookOptions | CallbackFunction<S_ABNORMALITY_BEGIN_4>, cb?: CallbackFunction<S_ABNORMALITY_BEGIN_4>);
  hook(packet: 'S_ACCOUNT_PACKAGE_LIST', version: 3 | '*', options?: HookOptions | CallbackFunction<S_ACCOUNT_PACKAGE_LIST_3>, cb?: CallbackFunction<S_ACCOUNT_PACKAGE_LIST_3>);
  hook(packet: 'S_APPLY_TITLE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_APPLY_TITLE_3>, cb?: CallbackFunction<S_APPLY_TITLE_3>);
  hook(packet: 'S_BOSS_GAGE_INFO', version: 3 | '*', options?: HookOptions | CallbackFunction<S_BOSS_GAGE_INFO_3>, cb?: CallbackFunction<S_BOSS_GAGE_INFO_3>);
  hook(packet: 'S_CAN_LOCKON_TARGET', version: 3 | '*', options?: HookOptions | CallbackFunction<S_CAN_LOCKON_TARGET_3>, cb?: CallbackFunction<S_CAN_LOCKON_TARGET_3>);
  hook(packet: 'S_CHAT', version: 3 | '*', options?: HookOptions | CallbackFunction<S_CHAT_3>, cb?: CallbackFunction<S_CHAT_3>);
  hook(packet: 'S_CONNECT_SKILL_ARROW', version: 3 | '*', options?: HookOptions | CallbackFunction<S_CONNECT_SKILL_ARROW_3>, cb?: CallbackFunction<S_CONNECT_SKILL_ARROW_3>);
  hook(packet: 'S_CREATURE_LIFE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_CREATURE_LIFE_3>, cb?: CallbackFunction<S_CREATURE_LIFE_3>);
  hook(packet: 'S_DECREASE_COOLTIME_SKILL', version: 3 | '*', options?: HookOptions | CallbackFunction<S_DECREASE_COOLTIME_SKILL_3>, cb?: CallbackFunction<S_DECREASE_COOLTIME_SKILL_3>);
  hook(packet: 'S_DEFEND_SUCCESS', version: 3 | '*', options?: HookOptions | CallbackFunction<S_DEFEND_SUCCESS_3>, cb?: CallbackFunction<S_DEFEND_SUCCESS_3>);
  hook(packet: 'S_DESPAWN_NPC', version: 3 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_NPC_3>, cb?: CallbackFunction<S_DESPAWN_NPC_3>);
  hook(packet: 'S_DESPAWN_USER', version: 3 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_USER_3>, cb?: CallbackFunction<S_DESPAWN_USER_3>);
  hook(packet: 'S_DIALOG', version: 3 | '*', options?: HookOptions | CallbackFunction<S_DIALOG_3>, cb?: CallbackFunction<S_DIALOG_3>);
  hook(packet: 'S_EXIT', version: 3 | '*', options?: HookOptions | CallbackFunction<S_EXIT_3>, cb?: CallbackFunction<S_EXIT_3>);
  hook(packet: 'S_FONT_SWAP_INFO', version: 3 | '*', options?: HookOptions | CallbackFunction<S_FONT_SWAP_INFO_3>, cb?: CallbackFunction<S_FONT_SWAP_INFO_3>);
  hook(packet: 'S_GRANT_SKILL', version: 3 | '*', options?: HookOptions | CallbackFunction<S_GRANT_SKILL_3>, cb?: CallbackFunction<S_GRANT_SKILL_3>);
  hook(packet: 'S_INSTANT_DASH', version: 3 | '*', options?: HookOptions | CallbackFunction<S_INSTANT_DASH_3>, cb?: CallbackFunction<S_INSTANT_DASH_3>);
  hook(packet: 'S_INSTANT_MOVE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_INSTANT_MOVE_3>, cb?: CallbackFunction<S_INSTANT_MOVE_3>);
  hook(packet: 'S_ITEMLIST', version: 3 | '*', options?: HookOptions | CallbackFunction<S_ITEMLIST_3>, cb?: CallbackFunction<S_ITEMLIST_3>);
  hook(packet: 'S_LOAD_TOPO', version: 3 | '*', options?: HookOptions | CallbackFunction<S_LOAD_TOPO_3>, cb?: CallbackFunction<S_LOAD_TOPO_3>);
  hook(packet: 'S_NPC_LOCATION', version: 3 | '*', options?: HookOptions | CallbackFunction<S_NPC_LOCATION_3>, cb?: CallbackFunction<S_NPC_LOCATION_3>);
  hook(packet: 'S_PARTY_MEMBER_ABNORMAL_ADD', version: 3 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_ABNORMAL_ADD_3>, cb?: CallbackFunction<S_PARTY_MEMBER_ABNORMAL_ADD_3>);
  hook(packet: 'S_PARTY_MEMBER_ABNORMAL_REFRESH', version: 3 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_ABNORMAL_REFRESH_3>, cb?: CallbackFunction<S_PARTY_MEMBER_ABNORMAL_REFRESH_3>);
  hook(packet: 'S_PARTY_MEMBER_INTERVAL_POS_UPDATE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_INTERVAL_POS_UPDATE_3>, cb?: CallbackFunction<S_PARTY_MEMBER_INTERVAL_POS_UPDATE_3>);
  hook(packet: 'S_PARTY_MEMBER_STAT_UPDATE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_STAT_UPDATE_3>, cb?: CallbackFunction<S_PARTY_MEMBER_STAT_UPDATE_3>);
  hook(packet: 'S_REGISTER_ENCHANT_ITEM', version: 3 | '*', options?: HookOptions | CallbackFunction<S_REGISTER_ENCHANT_ITEM_3>, cb?: CallbackFunction<S_REGISTER_ENCHANT_ITEM_3>);
  hook(packet: 'S_REGISTER_EVOLUTION_ITEM', version: 3 | '*', options?: HookOptions | CallbackFunction<S_REGISTER_EVOLUTION_ITEM_3>, cb?: CallbackFunction<S_REGISTER_EVOLUTION_ITEM_3>);
  hook(packet: 'S_REQUEST_SERVANT_INFO_LIST', version: 3 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_SERVANT_INFO_LIST_3>, cb?: CallbackFunction<S_REQUEST_SERVANT_INFO_LIST_3>);
  hook(packet: 'S_SHOW_HP', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SHOW_HP_3>, cb?: CallbackFunction<S_SHOW_HP_3>);
  hook(packet: 'S_SKILL_CATEGORY', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SKILL_CATEGORY_3>, cb?: CallbackFunction<S_SKILL_CATEGORY_3>);
  hook(packet: 'S_SPAWN_DOOR', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_DOOR_3>, cb?: CallbackFunction<S_SPAWN_DOOR_3>);
  hook(packet: 'S_SPAWN_ME', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_ME_3>, cb?: CallbackFunction<S_SPAWN_ME_3>);
  hook(packet: 'S_SPAWN_SHUTTLE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_SHUTTLE_3>, cb?: CallbackFunction<S_SPAWN_SHUTTLE_3>);
  hook(packet: 'S_SPAWN_WORKOBJECT', version: 3 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_WORKOBJECT_3>, cb?: CallbackFunction<S_SPAWN_WORKOBJECT_3>);
  hook(packet: 'S_START_ACTION_SCRIPT', version: 3 | '*', options?: HookOptions | CallbackFunction<S_START_ACTION_SCRIPT_3>, cb?: CallbackFunction<S_START_ACTION_SCRIPT_3>);
  hook(packet: 'S_START_CHANGE_USER_APPEARANCE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_START_CHANGE_USER_APPEARANCE_3>, cb?: CallbackFunction<S_START_CHANGE_USER_APPEARANCE_3>);
  hook(packet: 'S_START_COOLTIME_SKILL', version: 3 | '*', options?: HookOptions | CallbackFunction<S_START_COOLTIME_SKILL_3>, cb?: CallbackFunction<S_START_COOLTIME_SKILL_3>);
  hook(packet: 'S_START_PRODUCE', version: 3 | '*', options?: HookOptions | CallbackFunction<S_START_PRODUCE_3>, cb?: CallbackFunction<S_START_PRODUCE_3>);
  hook(packet: 'S_USER_STATUS', version: 3 | '*', options?: HookOptions | CallbackFunction<S_USER_STATUS_3>, cb?: CallbackFunction<S_USER_STATUS_3>);
  hook(packet: 'S_WHISPER', version: 3 | '*', options?: HookOptions | CallbackFunction<S_WHISPER_3>, cb?: CallbackFunction<S_WHISPER_3>);
  hook(packet: 'C_HIT_USER_PROJECTILE', version: 4 | '*', options?: HookOptions | CallbackFunction<C_HIT_USER_PROJECTILE_4>, cb?: CallbackFunction<C_HIT_USER_PROJECTILE_4>);
  hook(packet: 'C_NOTIFY_LOCATION_IN_ACTION', version: 4 | '*', options?: HookOptions | CallbackFunction<C_NOTIFY_LOCATION_IN_ACTION_4>, cb?: CallbackFunction<C_NOTIFY_LOCATION_IN_ACTION_4>);
  hook(packet: 'C_NOTIFY_LOCATION_IN_DASH', version: 4 | '*', options?: HookOptions | CallbackFunction<C_NOTIFY_LOCATION_IN_DASH_4>, cb?: CallbackFunction<C_NOTIFY_LOCATION_IN_DASH_4>);
  hook(packet: 'C_PLAYER_FLYING_LOCATION', version: 4 | '*', options?: HookOptions | CallbackFunction<C_PLAYER_FLYING_LOCATION_4>, cb?: CallbackFunction<C_PLAYER_FLYING_LOCATION_4>);
  hook(packet: 'C_PRESS_SKILL', version: 4 | '*', options?: HookOptions | CallbackFunction<C_PRESS_SKILL_4>, cb?: CallbackFunction<C_PRESS_SKILL_4>);
  hook(packet: 'C_TRY_LOOT_DROPITEM', version: 4 | '*', options?: HookOptions | CallbackFunction<C_TRY_LOOT_DROPITEM_4>, cb?: CallbackFunction<C_TRY_LOOT_DROPITEM_4>);
  hook(packet: 'S_CANNOT_START_SKILL', version: 4 | '*', options?: HookOptions | CallbackFunction<S_CANNOT_START_SKILL_4>, cb?: CallbackFunction<S_CANNOT_START_SKILL_4>);
  hook(packet: 'S_DESPAWN_DROPITEM', version: 4 | '*', options?: HookOptions | CallbackFunction<S_DESPAWN_DROPITEM_4>, cb?: CallbackFunction<S_DESPAWN_DROPITEM_4>);
  hook(packet: 'S_END_USER_PROJECTILE', version: 4 | '*', options?: HookOptions | CallbackFunction<S_END_USER_PROJECTILE_4>, cb?: CallbackFunction<S_END_USER_PROJECTILE_4>);
  hook(packet: 'S_INSTANCE_ARROW', version: 4 | '*', options?: HookOptions | CallbackFunction<S_INSTANCE_ARROW_4>, cb?: CallbackFunction<S_INSTANCE_ARROW_4>);
  hook(packet: 'S_PARTY_MEMBER_CHANGE_HP', version: 4 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_CHANGE_HP_4>, cb?: CallbackFunction<S_PARTY_MEMBER_CHANGE_HP_4>);
  hook(packet: 'S_REQUEST_SPAWN_SERVANT', version: 4 | '*', options?: HookOptions | CallbackFunction<S_REQUEST_SPAWN_SERVANT_4>, cb?: CallbackFunction<S_REQUEST_SPAWN_SERVANT_4>);
  hook(packet: 'S_SPAWN_COLLECTION', version: 4 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_COLLECTION_4>, cb?: CallbackFunction<S_SPAWN_COLLECTION_4>);
  hook(packet: 'S_START_CLIENT_CUSTOM_SKILL', version: 4 | '*', options?: HookOptions | CallbackFunction<S_START_CLIENT_CUSTOM_SKILL_4>, cb?: CallbackFunction<S_START_CLIENT_CUSTOM_SKILL_4>);
  hook(packet: 'S_START_INVERSE_CAPTURE', version: 4 | '*', options?: HookOptions | CallbackFunction<S_START_INVERSE_CAPTURE_4>, cb?: CallbackFunction<S_START_INVERSE_CAPTURE_4>);
  hook(packet: 'S_UPDATE_EVENT_SEED_STATE', version: 4 | '*', options?: HookOptions | CallbackFunction<S_UPDATE_EVENT_SEED_STATE_4>, cb?: CallbackFunction<S_UPDATE_EVENT_SEED_STATE_4>);
  hook(packet: 'C_PLAYER_LOCATION', version: 5 | '*', options?: HookOptions | CallbackFunction<C_PLAYER_LOCATION_5>, cb?: CallbackFunction<C_PLAYER_LOCATION_5>);
  hook(packet: 'C_START_INSTANCE_SKILL_EX', version: 5 | '*', options?: HookOptions | CallbackFunction<C_START_INSTANCE_SKILL_EX_5>, cb?: CallbackFunction<C_START_INSTANCE_SKILL_EX_5>);
  hook(packet: 'S_ACTION_END', version: 5 | '*', options?: HookOptions | CallbackFunction<S_ACTION_END_5>, cb?: CallbackFunction<S_ACTION_END_5>);
  hook(packet: 'S_SPAWN_PROJECTILE', version: 5 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_PROJECTILE_5>, cb?: CallbackFunction<S_SPAWN_PROJECTILE_5>);
  hook(packet: 'S_USER_LOCATION', version: 5 | '*', options?: HookOptions | CallbackFunction<S_USER_LOCATION_5>, cb?: CallbackFunction<S_USER_LOCATION_5>);
  hook(packet: 'C_START_COMBO_INSTANT_SKILL', version: 6 | '*', options?: HookOptions | CallbackFunction<C_START_COMBO_INSTANT_SKILL_6>, cb?: CallbackFunction<C_START_COMBO_INSTANT_SKILL_6>);
  hook(packet: 'S_CREATURE_CHANGE_HP', version: 6 | '*', options?: HookOptions | CallbackFunction<S_CREATURE_CHANGE_HP_6>, cb?: CallbackFunction<S_CREATURE_CHANGE_HP_6>);
  hook(packet: 'S_UNICAST_TRANSFORM_DATA', version: 6 | '*', options?: HookOptions | CallbackFunction<S_UNICAST_TRANSFORM_DATA_6>, cb?: CallbackFunction<S_UNICAST_TRANSFORM_DATA_6>);
  hook(packet: 'C_START_INSTANCE_SKILL', version: 7 | '*', options?: HookOptions | CallbackFunction<C_START_INSTANCE_SKILL_7>, cb?: CallbackFunction<C_START_INSTANCE_SKILL_7>);
  hook(packet: 'C_START_SKILL', version: 7 | '*', options?: HookOptions | CallbackFunction<C_START_SKILL_7>, cb?: CallbackFunction<C_START_SKILL_7>);
  hook(packet: 'C_START_TARGETED_SKILL', version: 7 | '*', options?: HookOptions | CallbackFunction<C_START_TARGETED_SKILL_7>, cb?: CallbackFunction<C_START_TARGETED_SKILL_7>);
  hook(packet: 'S_PARTY_MEMBER_LIST', version: 7 | '*', options?: HookOptions | CallbackFunction<S_PARTY_MEMBER_LIST_7>, cb?: CallbackFunction<S_PARTY_MEMBER_LIST_7>);
  hook(packet: 'S_USER_EXTERNAL_CHANGE', version: 7 | '*', options?: HookOptions | CallbackFunction<S_USER_EXTERNAL_CHANGE_7>, cb?: CallbackFunction<S_USER_EXTERNAL_CHANGE_7>);
  hook(packet: 'S_SPAWN_DROPITEM', version: 8 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_DROPITEM_8>, cb?: CallbackFunction<S_SPAWN_DROPITEM_8>);
  hook(packet: 'S_ACTION_STAGE', version: 9 | '*', options?: HookOptions | CallbackFunction<S_ACTION_STAGE_9>, cb?: CallbackFunction<S_ACTION_STAGE_9>);
  hook(packet: 'S_START_USER_PROJECTILE', version: 9 | '*', options?: HookOptions | CallbackFunction<S_START_USER_PROJECTILE_9>, cb?: CallbackFunction<S_START_USER_PROJECTILE_9>);
  hook(packet: 'S_SPAWN_NPC', version: 11 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_NPC_11>, cb?: CallbackFunction<S_SPAWN_NPC_11>);
  hook(packet: 'S_USER_PAPERDOLL_INFO', version: 11 | '*', options?: HookOptions | CallbackFunction<S_USER_PAPERDOLL_INFO_11>, cb?: CallbackFunction<S_USER_PAPERDOLL_INFO_11>);
  hook(packet: 'S_EACH_SKILL_RESULT', version: 14 | '*', options?: HookOptions | CallbackFunction<S_EACH_SKILL_RESULT_14>, cb?: CallbackFunction<S_EACH_SKILL_RESULT_14>);
  hook(packet: 'S_LOGIN', version: 14 | '*', options?: HookOptions | CallbackFunction<S_LOGIN_14>, cb?: CallbackFunction<S_LOGIN_14>);
  hook(packet: 'S_PLAYER_STAT_UPDATE', version: 14 | '*', options?: HookOptions | CallbackFunction<S_PLAYER_STAT_UPDATE_14>, cb?: CallbackFunction<S_PLAYER_STAT_UPDATE_14>);
  hook(packet: 'S_SHOW_ITEM_TOOLTIP', version: 14 | '*', options?: HookOptions | CallbackFunction<S_SHOW_ITEM_TOOLTIP_14>, cb?: CallbackFunction<S_SHOW_ITEM_TOOLTIP_14>);
  hook(packet: 'S_SPAWN_USER', version: 15 | '*', options?: HookOptions | CallbackFunction<S_SPAWN_USER_15>, cb?: CallbackFunction<S_SPAWN_USER_15>);
  hook(packet: 'S_GET_USER_LIST', version: 17 | '*', options?: HookOptions | CallbackFunction<S_GET_USER_LIST_17>, cb?: CallbackFunction<S_GET_USER_LIST_17>);
}
