import { Vec3, SkillId, Customize, PacketBase } from '../lib/Common'


export class C_REQUEST_PRIVATE_CHANNEL_INFO_2 extends PacketBase {
  /**
     Globally unique id generated by the server.  Default channel settings when created via chat UI :  - channelId : FF FF FF FF  - owner : 1  - password : 1000  - refer to S_REQUEST_PRIVATE_CHANNEL_INFO for above ^  Once user inputs name and password for private channel,  server generates channelId and updates password.
  */
  channelId: number
}
