import { Vec3, SkillId, Customize, PacketBase } from '../lib/Common'


export class S_PRIVATE_CHANNEL_NOTICE_2 extends PacketBase {
  /**
     globally unique id generated by the server
  */
  channelId: number

  /**
     SMT_PRIVATE_CHANNEL_{OPEN,ENTER,EXIT,CHIEF}
  */
  event: number

  /**
     can be empty
  */
  name: string
}
